// Generated by WebGPU-KTypes WGSL Backend

fn break_from_loop() {
    {
        var i: i32 = 0;
        while (true) {
            if ((i < 4)) {
                {
                    break;
                }
                i = 1;
            } else {
                break;
            }
        }
    }
}

@compute
fn main() {
}
