// Generated by WebGPU-KTypes WGSL Backend

fn break_from_loop() {
    {
        f32 local_0 = 0;
        while (true) {
            if ((local_0 < 4)) {
                {
                    break;
                }
                local_0 = 1;
            } else {
                break;
            }
        }
    }
}

fn main() {
}

@compute
fn main() {
}
