// Generated by WebGPU-KTypes WGSL Backend

fn f() {
    /* unknown type */ local_0 = /* unknown type */();
    vec4<f32> local_1 = vec4<f32>(0);
    i32 local_2 = 0;
    i32 local_3 = 0;
    local_1[0] = (local_0[local_3][1] * local_0[local_2][2]);
}

@compute
fn f() {
}
