// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    local_invocation_id: vec3<u32>,
    local_invocation_index: u32,
}
var<workgroup> wg_var: u32;

@compute
fn compute1(input: Struct_2) {
    wg_var = (input.local_invocation_index * 2);
    wg_var = input.local_invocation_id[0];
}
