// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> t: f32;
@group(0) @binding(1)
var<private> s: f32;
@group(0) @binding(2)
var<private> d: f32;
@group(0) @binding(3)
var<private> c: f32;
@group(0) @binding(4)
var<private> st: f32;

fn color() {
}

fn textureSample() {
}

fn textureSample() {
}

fn textureSampleLevel() {
}

fn textureSampleLevel() {
}

fn textureSampleGrad() {
}

fn textureSampleBias() {
}

fn depth() {
}

fn textureSampleLevel() {
}

fn textureSampleCompare() {
}

fn textureGatherCompare() {
}

fn () {
}

@fragment
fn main() {
}
