// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    f: f32,
    i: i32,
    u: u32,
}
var<private> xvipaiai: vec2<i32> = vec2<f32>(42, 43);
var<private> xvupaiai: vec2<u32> = vec2<f32>(44, 45);
var<private> xvfpaiai: vec2<f32> = vec2<f32>(46, 47);
var<private> xvfpafaf: vec2<f32> = vec2<f32>(48.0f, 49.0f);
var<private> xvfpaiaf: vec2<f32> = vec2<f32>(48, 49.0f);
var<private> xvupuai: vec2<u32> = vec2<f32>(0u, 43);
var<private> xvupaiu: vec2<u32> = vec2<f32>(42, 0u);
var<private> xvuuai: vec2<u32> = vec2<u32>(0u, 43);
var<private> xvuaiu: vec2<u32> = vec2<u32>(42, 0u);
var<private> xvip____: vec2<i32> = vec2<f32>();
var<private> xvup____: vec2<u32> = vec2<f32>();
var<private> xvfp____: vec2<f32> = vec2<f32>();
var<private> xmfp____: mat2x2<f32> = mat2x2<f32>(vec2<f32>(), vec2<f32>());
var<private> xmfpaiaiaiai: mat2x2<f32> = mat2x2<f32>(1, 2, 3, 4);
var<private> xmfpafaiaiai: mat2x2<f32> = mat2x2<f32>(1.0f, 2, 3, 4);
var<private> xmfpaiafaiai: mat2x2<f32> = mat2x2<f32>(1, 2.0f, 3, 4);
var<private> xmfpaiaiafai: mat2x2<f32> = mat2x2<f32>(1, 2, 3.0f, 4);
var<private> xmfpaiaiaiaf: mat2x2<f32> = mat2x2<f32>(1, 2, 3, 4.0f);
var<private> xaipaiai: array<i32, 2> = array<i32, 2>(1, 2);
var<private> xaupaiai: array<u32, 2> = array<i32, 2>(1, 2);
var<private> xafpaiaf: array<f32, 2> = array<i32, 2>(1, 2.0f);
var<private> xafpafai: array<f32, 2> = array<f32, 2>(1.0f, 2);
var<private> xafpafaf: array<f32, 2> = array<f32, 2>(1.0f, 2.0f);
var<private> xvisai: vec2<i32> = vec2<f32>(1);
var<private> xvusai: vec2<u32> = vec2<f32>(1);
var<private> xvfsai: vec2<f32> = vec2<f32>(1);
var<private> xvfsaf: vec2<f32> = vec2<f32>(1.0f);
var<private> s_f_i_u: Struct_3 = Struct_3(1.0f, 0, 0u);
var<private> s_f_iai: Struct_3 = Struct_3(1.0f, 0, 1);
var<private> s_fai_u: Struct_3 = Struct_3(1.0f, 1, 0u);
var<private> s_faiai: Struct_3 = Struct_3(1.0f, 1, 1);
var<private> saf_i_u: Struct_3 = Struct_3(1.0f, 0, 0u);
var<private> saf_iai: Struct_3 = Struct_3(1.0f, 0, 1);
var<private> safai_u: Struct_3 = Struct_3(1.0f, 1, 0u);
var<private> safaiai: Struct_3 = Struct_3(1.0f, 1, 1);
