// Generated by WebGPU-KTypes WGSL Backend
var<private> plus_fafaf: f32 = (1.0f + 2.0f);
var<private> plus_fafai: f32 = (1.0f + 2);
var<private> plus_faf_f: f32 = (1.0f + 2.0f);
var<private> plus_faiaf: f32 = (1 + 2.0f);
var<private> plus_faiai: f32 = (1 + 2);
var<private> plus_fai_f: f32 = (1 + 2.0f);
var<private> plus_f_faf: f32 = (1.0f + 2.0f);
var<private> plus_f_fai: f32 = (1.0f + 2);
var<private> plus_f_f_f: f32 = (1.0f + 2.0f);
var<private> plus_iaiai: i32 = (1 + 2);
var<private> plus_iai_i: i32 = (1 + 2);
var<private> plus_i_iai: i32 = (1 + 2);
var<private> plus_i_i_i: i32 = (1 + 2);
var<private> plus_uaiai: u32 = (1 + 2);
var<private> plus_uai_u: u32 = (1 + 2u);
var<private> plus_u_uai: u32 = (1u + 2);
var<private> plus_u_u_u: u32 = (1u + 2u);
var<private> bitflip_u_u: u32 = ~(0u);
var<private> bitflip_uai: u32 = (~(0) & (0 - 1));
var<private> least_i32: i32 = -(-2147483648);
var<private> least_f32: f32 = -(3.4028235E38f);
var<private> shl_iaiai: i32 = (1 << 2);
var<private> shl_iai_u: i32 = (1 << 2u);
var<private> shl_uaiai: u32 = (1 << 2);
var<private> shl_uai_u: u32 = (1 << 2u);
var<private> shlaiaiai: i32 = (1 << 2);
var<private> shlaiai_u: i32 = (1 << 2u);
var<private> shr_iaiai: i32 = (1 >> 2);
var<private> shr_iai_u: i32 = (1 >> 2u);
var<private> shr_uaiai: u32 = (1 >> 2);
var<private> shr_uai_u: u32 = (1 >> 2u);
var<private> shraiaiai: i32 = (1 >> 2);
var<private> shraiai_u: i32 = (1 >> 2u);
var<private> wgpu_4492: i32 = i32(-(0));
var<private> wgpu_4492_2: i32 = -(-2147483648);
var<workgroup> a: array<u32, 64>;

fn runtime_values() {
    var f: f32 = 42;
    var i: i32 = 43;
    var u: u32 = 44;
    var plus_fafaf: f32 = (1.0f + 2.0f);
    var plus_fafai: f32 = (1.0f + 2);
    var plus_faf_f: f32 = (1.0f + f);
    var plus_faiaf: f32 = (1 + 2.0f);
    var plus_faiai: f32 = (1 + 2);
    var plus_fai_f: f32 = (1 + f);
    var plus_f_faf: f32 = (f + 2.0f);
    var plus_f_fai: f32 = (f + 2);
    var plus_f_f_f: f32 = (f + f);
    var plus_iaiai: i32 = (1 + 2);
    var plus_iai_i: i32 = (1 + i);
    var plus_i_iai: i32 = (i + 2);
    var plus_i_i_i: i32 = (i + i);
    var plus_uaiai: u32 = (1 + 2);
    var plus_uai_u: u32 = (1 + u);
    var plus_u_uai: u32 = (u + 2);
    var plus_u_u_u: u32 = (u + u);
    var shl_iai_u: i32 = (1 << u);
    var shr_iai_u: i32 = (1 << u);
}

fn wgpu_4445() {
    var a: f32 = (((3.0f * 2.0f) - 1.0f) * 1.0f);
    var b: f32 = (((3.0f * 2.0f) + 1.0f) * 1.0f);
    var c: f32 = (((3.0f * 2.0f) - 1.0f) * 1.0f);
}

fn wgpu_4435() {
    var x: i32 = 1;
    var y: u32 = a[(x - 1)];
}

@compute
fn main() {
    runtime_values();
    wgpu_4445();
    wgpu_4435();
}
