// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<storage, read_write> atomic_i32: i32;
@group(0) @binding(1)
var<storage, read_write> atomic_u32: u32;

fn test_atomic_i32() {
}

fn atomicStore() {
}

fn atomicCompareExchangeWeak() {
}

fn atomicCompareExchangeWeak() {
}

fn atomicAdd() {
}

fn atomicSub() {
}

fn atomicAnd() {
}

fn atomicXor() {
}

fn atomicOr() {
}

fn atomicMin() {
}

fn atomicMax() {
}

fn atomicExchange() {
}

fn test_atomic_u32() {
}

fn atomicStore() {
}

fn atomicCompareExchangeWeak() {
}

fn atomicCompareExchangeWeak() {
}

fn atomicAdd() {
}

fn atomicSub() {
}

fn atomicAnd() {
}

fn atomicXor() {
}

fn atomicOr() {
}

fn atomicMin() {
}

fn atomicMax() {
}

fn atomicExchange() {
}

@compute
fn main() {
}
