// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> t: texture_2d<f32>;
@group(0) @binding(1)
var<private> s: sampler;
@group(0) @binding(2)
var<private> d: texture_depth_2d;
@group(0) @binding(3)
var<private> c: sampler_comparison;
@group(0) @binding(4)
var<private> st: texture_storage_2d<rgba8unorm, read_write>;

fn color() {
    textureSample(t, s, vec2<f32>(1, 2));
    textureSample(t, s, vec2<f32>(1, 2), vec2<f32>(3, 4));
    textureSampleLevel(t, s, vec2<f32>(1, 2), 0);
    textureSampleLevel(t, s, vec2<f32>(1, 2), 0.0f);
    textureSampleGrad(t, s, vec2<f32>(1, 2), vec2<f32>(3, 4), vec2<f32>(5, 6));
    textureSampleBias(t, s, vec2<f32>(1, 2), 1);
}

fn textureSample(arg_0: texture_2d<f32>, arg_1: sampler, arg_2: vec2<f32>) -> vec4<f32> {
}

fn textureSample(arg_0: texture_2d<f32>, arg_1: sampler, arg_2: vec2<f32>, arg_3: vec2<f32>) -> vec4<f32> {
}

fn textureSampleLevel(arg_0: texture_2d<f32>, arg_1: sampler, arg_2: vec2<f32>, arg_3: i32) -> vec4<f32> {
}

fn textureSampleLevel(arg_0: texture_2d<f32>, arg_1: sampler, arg_2: vec2<f32>, arg_3: f32) -> vec4<f32> {
}

fn textureSampleGrad(arg_0: texture_2d<f32>, arg_1: sampler, arg_2: vec2<f32>, arg_3: vec2<f32>, arg_4: vec2<f32>) -> vec4<f32> {
}

fn textureSampleBias(arg_0: texture_2d<f32>, arg_1: sampler, arg_2: vec2<f32>, arg_3: i32) -> vec4<f32> {
}

fn depth() {
    textureSampleLevel(d, s, vec2<f32>(1, 2), 1);
    textureSampleCompare(d, c, vec2<f32>(1, 2), 0);
    textureGatherCompare(d, c, vec2<f32>(1, 2), 0);
}

fn textureSampleLevel(arg_0: texture_depth_2d, arg_1: sampler, arg_2: vec2<f32>, arg_3: i32) -> vec4<f32> {
}

fn textureSampleCompare(arg_0: texture_depth_2d, arg_1: sampler_comparison, arg_2: vec2<f32>, arg_3: i32) -> f32 {
}

fn textureGatherCompare(arg_0: texture_depth_2d, arg_1: sampler_comparison, arg_2: vec2<f32>, arg_3: i32) -> texture_depth_2d {
}

fn storage() {
    textureStore(st, vec2<f32>(0, 1), vec4<f32>(2, 3, 4, 5));
}

fn textureStore(arg_0: texture_storage_2d<rgba8unorm, read_write>, arg_1: vec2<f32>, arg_2: vec4<f32>) -> texture_storage_2d<rgba8unorm, read_write> {
}

@fragment
fn main() {
    color();
    depth();
    storage();
}
