// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    inner: /* unknown type */,
}
@group(0) @binding(0)
var<storage> global_0: Struct_2;

fn cs_main() {
    Struct_2 local_0 = global_0;
}

@compute
fn cs_main() {
}
