// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> image: texture_storage_2d<r64uint>;

fn textureAtomicMax(arg_0: texture_storage_2d<r64uint>, arg_1: vec2<i32>, arg_2: u64) -> texture_storage_2d<r64uint> {
}

fn workgroupBarrier() {
}

fn textureAtomicMin(arg_0: texture_storage_2d<r64uint>, arg_1: vec2<i32>, arg_2: u64) -> texture_storage_2d<r64uint> {
}

@compute
fn cs_main(id: vec3<u32>) {
    textureAtomicMax(image, vec2<i32>(0, 0), 1u);
    workgroupBarrier();
    textureAtomicMin(image, vec2<i32>(0, 0), 1u);
}
