// Generated by WebGPU-KTypes WGSL Backend
struct Struct_7 {
    old_value: i32,
    exchanged: bool,
}
struct Struct_9 {
    old_value: u32,
    exchanged: bool,
}
var<private> SIZE: u32 = 128u;
@group(0) @binding(0)
var<storage, read_write> arr_i32: array<i32>;
@group(0) @binding(1)
var<storage, read_write> arr_u32: array<u32>;

fn atomicLoad(arg_0: ptr<function, i32>) -> ptr<function, i32> {
}

fn atomicCompareExchangeWeak(arg_0: ptr<function, i32>, arg_1: ptr<function, i32>, arg_2: i32) -> Struct_7 {
}

fn atomicLoad(arg_0: ptr<function, u32>) -> ptr<function, u32> {
}

fn atomicCompareExchangeWeak(arg_0: ptr<function, u32>, arg_1: ptr<function, u32>, arg_2: u32) -> Struct_9 {
}

@compute
fn test_atomic_compare_exchange_i32() {
    {
        var i: u32 = 0u;
        loop {
            if ((i < SIZE)) {
                {
                    var old: ptr<function, i32> = atomicLoad(&arr_i32[i]);
                    var exchanged: bool = false;
                    loop {
                        if (!(exchanged)) {
                            var new_: i32 = bitcast<i32>((bitcast<f32>(old) + 1.0f));
                            var result: Struct_7 = atomicCompareExchangeWeak(&arr_i32[i], old, new_);
                            old = result.old_value;
                            exchanged = result.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
}

@compute
fn test_atomic_compare_exchange_u32() {
    {
        var i: u32 = 0u;
        loop {
            if ((i < SIZE)) {
                {
                    var old: ptr<function, u32> = atomicLoad(&arr_u32[i]);
                    var exchanged: bool = false;
                    loop {
                        if (!(exchanged)) {
                            var new_: u32 = bitcast<u32>((bitcast<f32>(old) + 1.0f));
                            var result: Struct_9 = atomicCompareExchangeWeak(&arr_u32[i], old, new_);
                            old = result.old_value;
                            exchanged = result.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
}
