// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> image_u: texture_storage_2d<r32uint>;
@group(0) @binding(1)
var<private> image_s: texture_storage_2d<r32sint>;

fn textureAtomicMax(arg_0: texture_storage_2d<r32uint>, arg_1: vec2<i32>, arg_2: u32) -> texture_storage_2d<r32uint> {
}

fn textureAtomicMin(arg_0: texture_storage_2d<r32uint>, arg_1: vec2<i32>, arg_2: u32) -> texture_storage_2d<r32uint> {
}

fn textureAtomicAdd(arg_0: texture_storage_2d<r32uint>, arg_1: vec2<i32>, arg_2: u32) -> texture_storage_2d<r32uint> {
}

fn textureAtomicAnd(arg_0: texture_storage_2d<r32uint>, arg_1: vec2<i32>, arg_2: u32) -> texture_storage_2d<r32uint> {
}

fn textureAtomicOr(arg_0: texture_storage_2d<r32uint>, arg_1: vec2<i32>, arg_2: u32) -> texture_storage_2d<r32uint> {
}

fn textureAtomicXor(arg_0: texture_storage_2d<r32uint>, arg_1: vec2<i32>, arg_2: u32) -> texture_storage_2d<r32uint> {
}

fn textureAtomicMax(arg_0: texture_storage_2d<r32sint>, arg_1: vec2<i32>, arg_2: i32) -> texture_storage_2d<r32sint> {
}

fn textureAtomicMin(arg_0: texture_storage_2d<r32sint>, arg_1: vec2<i32>, arg_2: i32) -> texture_storage_2d<r32sint> {
}

fn textureAtomicAdd(arg_0: texture_storage_2d<r32sint>, arg_1: vec2<i32>, arg_2: i32) -> texture_storage_2d<r32sint> {
}

fn textureAtomicAnd(arg_0: texture_storage_2d<r32sint>, arg_1: vec2<i32>, arg_2: i32) -> texture_storage_2d<r32sint> {
}

fn textureAtomicOr(arg_0: texture_storage_2d<r32sint>, arg_1: vec2<i32>, arg_2: i32) -> texture_storage_2d<r32sint> {
}

fn textureAtomicXor(arg_0: texture_storage_2d<r32sint>, arg_1: vec2<i32>, arg_2: i32) -> texture_storage_2d<r32sint> {
}

@compute
fn cs_main(id: vec3<u32>) {
    textureAtomicMax(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicMin(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicAdd(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicAnd(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicOr(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicXor(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicMax(image_s, vec2<i32>(0, 0), 1);
    textureAtomicMin(image_s, vec2<i32>(0, 0), 1);
    textureAtomicAdd(image_s, vec2<i32>(0, 0), 1);
    textureAtomicAnd(image_s, vec2<i32>(0, 0), 1);
    textureAtomicOr(image_s, vec2<i32>(0, 0), 1);
    textureAtomicXor(image_s, vec2<i32>(0, 0), 1);
}
