// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    atomic_scalar: u32,
    atomic_arr: array<i32>,
}
@group(0) @binding(0)
var<storage, read_write> storage_atomic_scalar: u32;
@group(0) @binding(1)
var<storage, read_write> storage_atomic_arr: array<i32>;
var<workgroup> workgroup_atomic_scalar: u32;
var<workgroup> workgroup_atomic_arr: array<i32>;
@group(0) @binding(2)
var<storage, read_write> storage_struct: Struct_3;
var<workgroup> workgroup_struct: Struct_3;

fn atomicStore() {
}

fn atomicStore() {
}

fn atomicStore() {
}

fn atomicStore() {
}

fn atomicStore() {
}

fn atomicStore() {
}

fn atomicStore() {
}

fn atomicStore() {
}

fn workgroupBarrier() {
}

fn atomicLoad() {
}

fn atomicLoad() {
}

fn atomicLoad() {
}

fn atomicLoad() {
}

fn atomicLoad() {
}

fn atomicLoad() {
}

fn atomicLoad() {
}

fn atomicLoad() {
}

fn workgroupBarrier() {
}

fn atomicAdd() {
}

fn atomicAdd() {
}

fn atomicAdd() {
}

fn atomicAdd() {
}

fn atomicAdd() {
}

fn atomicAdd() {
}

fn atomicAdd() {
}

fn atomicAdd() {
}

fn workgroupBarrier() {
}

fn atomicSub() {
}

fn atomicSub() {
}

fn atomicSub() {
}

fn atomicSub() {
}

fn atomicSub() {
}

fn atomicSub() {
}

fn atomicSub() {
}

fn atomicSub() {
}

fn workgroupBarrier() {
}

fn atomicMax() {
}

fn atomicMax() {
}

fn atomicMax() {
}

fn atomicMax() {
}

fn atomicMax() {
}

fn atomicMax() {
}

fn atomicMax() {
}

fn atomicMax() {
}

fn workgroupBarrier() {
}

fn atomicMin() {
}

fn atomicMin() {
}

fn atomicMin() {
}

fn atomicMin() {
}

fn atomicMin() {
}

fn atomicMin() {
}

fn atomicMin() {
}

fn atomicMin() {
}

fn workgroupBarrier() {
}

fn atomicAnd() {
}

fn atomicAnd() {
}

fn atomicAnd() {
}

fn atomicAnd() {
}

fn atomicAnd() {
}

fn atomicAnd() {
}

fn atomicAnd() {
}

fn atomicAnd() {
}

fn workgroupBarrier() {
}

fn atomicOr() {
}

fn atomicOr() {
}

fn atomicOr() {
}

fn atomicOr() {
}

fn atomicOr() {
}

fn atomicOr() {
}

fn atomicOr() {
}

fn atomicOr() {
}

fn workgroupBarrier() {
}

fn atomicXor() {
}

fn atomicXor() {
}

fn atomicXor() {
}

fn atomicXor() {
}

fn atomicXor() {
}

fn atomicXor() {
}

fn atomicXor() {
}

fn atomicXor() {
}

fn atomicExchange() {
}

fn atomicExchange() {
}

fn atomicExchange() {
}

fn atomicExchange() {
}

fn atomicExchange() {
}

fn atomicExchange() {
}

fn atomicExchange() {
}

fn atomicExchange() {
}

fn atomicCompareExchangeWeak() {
}

fn atomicCompareExchangeWeak() {
}

fn atomicCompareExchangeWeak() {
}

fn atomicCompareExchangeWeak() {
}

fn atomicCompareExchangeWeak() {
}

fn atomicCompareExchangeWeak() {
}

fn atomicCompareExchangeWeak() {
}

fn atomicCompareExchangeWeak() {
}

@compute
fn cs_main(id: vec3<u32>) {
    var l0: ptr<function, u32> = atomicLoad(/* unsupported expression: ValuePointer */);
    var l1: ptr<function, i32> = atomicLoad(/* unsupported expression: ValuePointer */);
    var l2: ptr<function, u32> = atomicLoad(/* unsupported expression: ValuePointer */);
    var l3: ptr<function, i32> = atomicLoad(/* unsupported expression: ValuePointer */);
    var l4: ptr<function, u32> = atomicLoad(/* unsupported expression: ValuePointer */);
    var l5: ptr<function, i32> = atomicLoad(/* unsupported expression: ValuePointer */);
    var l6: ptr<function, u32> = atomicLoad(/* unsupported expression: ValuePointer */);
    var l7: ptr<function, i32> = atomicLoad(/* unsupported expression: ValuePointer */);
    var cas_res_0: ptr<function, u32> = atomicCompareExchangeWeak(/* unsupported expression: ValuePointer */, 0u, 0u);
    var cas_res_1: ptr<function, i32> = atomicCompareExchangeWeak(/* unsupported expression: ValuePointer */, 0, 0);
    var cas_res_2: ptr<function, u32> = atomicCompareExchangeWeak(/* unsupported expression: ValuePointer */, 0u, 0u);
    var cas_res_3: ptr<function, i32> = atomicCompareExchangeWeak(/* unsupported expression: ValuePointer */, 0, 0);
    var cas_res_4: ptr<function, u32> = atomicCompareExchangeWeak(/* unsupported expression: ValuePointer */, 0u, 0u);
    var cas_res_5: ptr<function, i32> = atomicCompareExchangeWeak(/* unsupported expression: ValuePointer */, 0, 0);
    var cas_res_6: ptr<function, u32> = atomicCompareExchangeWeak(/* unsupported expression: ValuePointer */, 0u, 0u);
    var cas_res_7: ptr<function, i32> = atomicCompareExchangeWeak(/* unsupported expression: ValuePointer */, 0, 0);
}
