// Generated by WebGPU-KTypes WGSL Backend
struct Struct_7 {
    old_value: i64,
    exchanged: bool,
}
struct Struct_9 {
    old_value: u64,
    exchanged: bool,
}
var<private> SIZE: u32 = 128u;
@group(0) @binding(0)
var<storage, read_write> arr_i64: array<i64>;
@group(0) @binding(1)
var<storage, read_write> arr_u64: array<u64>;

fn atomicLoad(arg_0: ptr<function, i64>) -> ptr<function, i64> {
}

fn atomicCompareExchangeWeak(arg_0: ptr<function, i64>, arg_1: i64, arg_2: i64) -> Struct_7 {
}

fn atomicLoad(arg_0: ptr<function, u64>) -> ptr<function, u64> {
}

fn atomicCompareExchangeWeak(arg_0: ptr<function, u64>, arg_1: u64, arg_2: u64) -> Struct_9 {
}

@compute
fn test_atomic_compare_exchange_i64() {
    {
        var i: u32 = 0u;
        loop {
            if ((i < SIZE)) {
                {
                    var old: i64 = atomicLoad(&arr_i64[i]);
                    var exchanged: bool = false;
                    loop {
                        if (!(exchanged)) {
                            var new_: i64 = bitcast<i64>((old + 10));
                            var result: Struct_7 = atomicCompareExchangeWeak(&arr_i64[i], old, new_);
                            old = result.old_value;
                            exchanged = result.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
}

@compute
fn test_atomic_compare_exchange_u64() {
    {
        var i: u32 = 0u;
        loop {
            if ((i < SIZE)) {
                {
                    var old: u64 = atomicLoad(&arr_u64[i]);
                    var exchanged: bool = false;
                    loop {
                        if (!(exchanged)) {
                            var new_: u64 = bitcast<u64>((old + 10u));
                            var result: Struct_9 = atomicCompareExchangeWeak(&arr_u64[i], old, new_);
                            old = result.old_value;
                            exchanged = result.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
}
