// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    atomic_scalar: f32,
    atomic_arr: array<f32, 2>,
}
@group(0) @binding(0)
var<storage, read_write> storage_atomic_scalar: f32;
@group(0) @binding(1)
var<storage, read_write> storage_atomic_arr: array<f32, 2>;
@group(0) @binding(2)
var<storage, read_write> storage_struct: Struct_2;

fn atomicStore() {
}

fn atomicStore() {
}

fn atomicStore() {
}

fn atomicStore() {
}

fn workgroupBarrier() {
}

fn atomicLoad() {
}

fn atomicLoad() {
}

fn atomicLoad() {
}

fn atomicLoad() {
}

fn workgroupBarrier() {
}

fn atomicAdd() {
}

fn atomicAdd() {
}

fn atomicAdd() {
}

fn atomicAdd() {
}

fn workgroupBarrier() {
}

fn atomicExchange() {
}

fn atomicExchange() {
}

fn atomicExchange() {
}

fn atomicExchange() {
}

@compute
fn cs_main(id: vec3<u32>) {
    var l0: ptr<function, f32> = atomicLoad(&storage_atomic_scalar);
    var l1: ptr<function, f32> = atomicLoad(&storage_atomic_arr[1]);
    var l2: ptr<function, f32> = atomicLoad(&storage_struct.atomic_scalar);
    var l3: ptr<function, f32> = atomicLoad(&storage_struct.atomic_arr[1]);
}
