// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    atomic_scalar: u64,
    atomic_arr: array<u64, 2>,
}
@group(0) @binding(0)
var<storage, read_write> storage_atomic_scalar: u64;
@group(0) @binding(1)
var<storage, read_write> storage_atomic_arr: array<u64, 2>;
@group(0) @binding(3)
var<uniform> input: u64;
@group(0) @binding(2)
var<storage, read_write> storage_struct: Struct_2;

fn atomicMax(arg_0: ptr<function, u64>, arg_1: u64) -> ptr<function, u64> {
}

fn atomicMax(arg_0: ptr<function, u64>, arg_1: i32) -> ptr<function, u64> {
}

fn atomicMax(arg_0: ptr<function, u64>, arg_1: u64) -> ptr<function, u64> {
}

fn atomicMax(arg_0: ptr<function, u64>, arg_1: u64) -> ptr<function, u64> {
}

fn workgroupBarrier() {
}

fn atomicMin(arg_0: ptr<function, u64>, arg_1: u64) -> ptr<function, u64> {
}

fn atomicMin(arg_0: ptr<function, u64>, arg_1: i32) -> ptr<function, u64> {
}

fn atomicMin(arg_0: ptr<function, u64>, arg_1: u64) -> ptr<function, u64> {
}

fn atomicMin(arg_0: ptr<function, u64>, arg_1: u64) -> ptr<function, u64> {
}

@compute
fn cs_main(id: vec3<u32>) {
    atomicMax(&storage_atomic_scalar, input);
    atomicMax(&storage_atomic_arr[1], (1 + input));
    atomicMax(&storage_struct.atomic_scalar, 1u);
    atomicMax(&storage_struct.atomic_arr[1], u64(id[0]));
    workgroupBarrier();
    atomicMin(&storage_atomic_scalar, input);
    atomicMin(&storage_atomic_arr[1], (1 + input));
    atomicMin(&storage_struct.atomic_scalar, 1u);
    atomicMin(&storage_struct.atomic_arr[1], u64(id[0]));
}
