// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> image_depth_2d: f32;
@group(0) @binding(1)
var<private> image_depth_2d_array: f32;
@group(0) @binding(2)
var<private> image_depth_multisampled_2d: f32;

fn test_textureLoad_depth_2d(coords: vec2<i32>, level: i32) -> f32 {
    return textureLoad(image_depth_2d, coords, level);
}

fn textureLoad() {
}

fn test_textureLoad_depth_2d_array_u(coords: vec2<i32>, index: u32, level: i32) -> f32 {
    return textureLoad(image_depth_2d_array, coords, index, level);
}

fn textureLoad() {
}

fn test_textureLoad_depth_2d_array_s(coords: vec2<i32>, index: i32, level: i32) -> f32 {
    return textureLoad(image_depth_2d_array, coords, index, level);
}

fn textureLoad() {
}

fn test_textureLoad_depth_multisampled_2d(coords: vec2<i32>, _sample: i32) -> f32 {
    return textureLoad(image_depth_multisampled_2d, coords, _sample);
}

fn textureLoad() {
}

@fragment
fn fragment_shader() -> vec4<f32> {
    return vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
}
