// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    a: u32,
    b: array<u32, 10>,
    c: array<u32>,
}
@group(0) @binding(0)
var<storage, read_write> globals: Struct_3;

fn fetch_add_atomic() -> u32 {
    return atomicAdd(&globals.a, 0u);
}

fn atomicAdd() {
}

fn fetch_add_atomic_static_sized_array(i: i32) -> u32 {
    return atomicAdd(&globals.b[i], 0u);
}

fn atomicAdd() {
}

fn fetch_add_atomic_dynamic_sized_array(i: i32) -> u32 {
    return atomicAdd(&globals.c[i], 0u);
}

fn atomicAdd() {
}

fn exchange_atomic() -> u32 {
    return atomicExchange(&globals.a, 0u);
}

fn atomicExchange() {
}

fn exchange_atomic_static_sized_array(i: i32) -> u32 {
    return atomicExchange(&globals.b[i], 0u);
}

fn atomicExchange() {
}

fn exchange_atomic_dynamic_sized_array(i: i32) -> u32 {
    return atomicExchange(&globals.c[i], 0u);
}

fn atomicExchange() {
}

fn fetch_add_atomic_dynamic_sized_array_static_index() -> u32 {
    return atomicAdd(&globals.c[1000], 0u);
}

fn atomicAdd() {
}

fn exchange_atomic_dynamic_sized_array_static_index() -> u32 {
    return atomicExchange(&globals.c[1000], 0u);
}

fn atomicExchange() {
}

@compute
fn main() {
}
