// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> image_depth_2d: texture_depth_2d;
@group(0) @binding(1)
var<private> image_depth_2d_array: texture_depth_2d_array;
@group(0) @binding(2)
var<private> image_depth_multisampled_2d: texture_depth_multisampled_2d;

fn test_textureLoad_depth_2d(coords: vec2<i32>, level: i32) -> f32 {
    return textureLoad(image_depth_2d, coords, level);
}

fn textureLoad(arg_0: texture_depth_2d, arg_1: vec2<i32>, arg_2: i32) -> texture_depth_2d {
}

fn test_textureLoad_depth_2d_array_u(coords: vec2<i32>, index: u32, level: i32) -> f32 {
    return textureLoad(image_depth_2d_array, coords, index, level);
}

fn textureLoad(arg_0: texture_depth_2d_array, arg_1: vec2<i32>, arg_2: u32, arg_3: i32) -> texture_depth_2d_array {
}

fn test_textureLoad_depth_2d_array_s(coords: vec2<i32>, index: i32, level: i32) -> f32 {
    return textureLoad(image_depth_2d_array, coords, index, level);
}

fn textureLoad(arg_0: texture_depth_2d_array, arg_1: vec2<i32>, arg_2: i32, arg_3: i32) -> texture_depth_2d_array {
}

fn test_textureLoad_depth_multisampled_2d(coords: vec2<i32>, _sample: i32) -> f32 {
    return textureLoad(image_depth_multisampled_2d, coords, _sample);
}

fn textureLoad(arg_0: texture_depth_multisampled_2d, arg_1: vec2<i32>, arg_2: i32) -> texture_depth_multisampled_2d {
}

@fragment
fn fragment_shader() -> vec4<f32> {
    test_textureLoad_depth_2d(vec2<i32>(), 0);
    test_textureLoad_depth_2d_array_u(vec2<i32>(), 0u, 0);
    test_textureLoad_depth_2d_array_s(vec2<i32>(), 0, 0);
    test_textureLoad_depth_multisampled_2d(vec2<i32>(), 0);
    return vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
}
