// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> image_1d: texture_1d<f32>;
@group(0) @binding(1)
var<private> image_2d: texture_2d<f32>;
@group(0) @binding(2)
var<private> image_2d_array: texture_2d_array<f32>;
@group(0) @binding(3)
var<private> image_3d: texture_3d<f32>;
@group(0) @binding(4)
var<private> image_multisampled_2d: texture_multisampled_2d<f32>;
@group(0) @binding(5)
var<private> image_storage_1d: texture_storage_1d<rgba8unorm, write>;
@group(0) @binding(6)
var<private> image_storage_2d: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(7)
var<private> image_storage_2d_array: texture_storage_2d_array<rgba8unorm, write>;
@group(0) @binding(8)
var<private> image_storage_3d: texture_storage_3d<rgba8unorm, write>;

fn test_textureLoad_1d(coords: i32, level: i32) -> vec4<f32> {
    return textureLoad(image_1d, coords, level);
}

fn textureLoad() {
}

fn test_textureLoad_2d(coords: vec2<i32>, level: i32) -> vec4<f32> {
    return textureLoad(image_2d, coords, level);
}

fn textureLoad() {
}

fn test_textureLoad_2d_array_u(coords: vec2<i32>, index: u32, level: i32) -> vec4<f32> {
    return textureLoad(image_2d_array, coords, index, level);
}

fn textureLoad() {
}

fn test_textureLoad_2d_array_s(coords: vec2<i32>, index: i32, level: i32) -> vec4<f32> {
    return textureLoad(image_2d_array, coords, index, level);
}

fn textureLoad() {
}

fn test_textureLoad_3d(coords: vec3<i32>, level: i32) -> vec4<f32> {
    return textureLoad(image_3d, coords, level);
}

fn textureLoad() {
}

fn test_textureLoad_multisampled_2d(coords: vec2<i32>, _sample: i32) -> vec4<f32> {
    return textureLoad(image_multisampled_2d, coords, _sample);
}

fn textureLoad() {
}

fn test_textureStore_1d(coords: i32, value: vec4<f32>) {
}

fn textureStore() {
}

fn test_textureStore_2d(coords: vec2<i32>, value: vec4<f32>) {
}

fn textureStore() {
}

fn test_textureStore_2d_array_u(coords: vec2<i32>, array_index: u32, value: vec4<f32>) {
}

fn textureStore() {
}

fn test_textureStore_2d_array_s(coords: vec2<i32>, array_index: i32, value: vec4<f32>) {
}

fn textureStore() {
}

fn test_textureStore_3d(coords: vec3<i32>, value: vec4<f32>) {
}

fn textureStore() {
}

@fragment
fn fragment_shader() -> vec4<f32> {
    return vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
}
