// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    position: vec4<f32>,
    clip_distances: /* unknown type */,
}

fn main() -> Struct_3 {
    Struct_3 local_0;
    local_0.clip_distances[0] = 0.5f;
    return local_0;
}

@vertex
fn main() -> Struct_3 {
}
