// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    data: array<u32>,
}
@group(0) @binding(0)
var<storage, read_write> v_indices: Struct_2;

fn collatz_iterations(n_base: u32) -> u32 {
    var n: u32 = n_base;
    var i: u32 = 0u;
    while (true) {
        if ((n > 0u)) {
            if (((n % 0u) == 0u)) {
                n = (n / 0u);
            } else {
                n = ((0u * n) + 0u);
            }
            i = (i + 0u);
        } else {
            break;
        }
    }
    return i;
}

@compute
fn main(global_id: vec3<u32>) {
    v_indices.data[global_id[0]] = collatz_iterations(v_indices.data[global_id[0]]);
}
