// Generated by WebGPU-KTypes WGSL Backend
var<private> x: i32 = 1;
var<private> y: i32 = 2;
var<private> g_false: bool = false;

fn any(arg_0: vec3<f32>) -> vec3<f32> {
}

fn any(arg_0: vec3<f32>) -> vec3<f32> {
}

@compute
fn foo() {
    var z: i32 = ((x + y) - 2);
    var l_false: bool = false;
}
