// Generated by WebGPU-KTypes WGSL Backend
var<private> ic0: vec2<f32> = (vec2<f32>(1, 1) + vec2<f32>(1.0f, 1.0f));

@compute
fn main() {
    var ic0: vec2<f32> = (vec2<f32>(1, 1) + vec2<f32>(1.0f, 1.0f));
    var lc0: vec2<f32> = (vec2<f32>(1, 1) + vec2<f32>(1.0f, 1.0f));
    var vc0: vec2<f32> = (vec2<f32>(1, 1) + vec2<f32>(1.0f, 1.0f));
}
