// Generated by WebGPU-KTypes WGSL Backend

fn cross(arg_0: vec3<f32>, arg_1: vec3<f32>) -> vec3<f32> {
}

@compute
fn main() {
    var a: vec3<f32> = cross(vec3<f32>(1.0f, 0.0f, 0.0f), vec3<f32>(0.0f, 1.0f, 0.0f));
}
