// Generated by WebGPU-KTypes WGSL Backend
struct Struct_1 {
    draw_index: u32,
}

@vertex
fn vertex(input: Struct_1) -> vec4<f32> {
    return vec4<f32>(f32(input.draw_index), 1.0f, 1.0f, 1.0f);
}
