// Generated by WebGPU-KTypes WGSL Backend
var<private> global_0: f32 = 1;
var<private> global_1: f32 = 0.0f;

fn f(x: f32) -> f32 {
    f32 local_0 = (0.0f + 0.0f);
    f32 local_1 = (local_0 + f32(5));
    f32 local_2 = -(0.0f);
    return (((x + local_0) + global_1) + 0.0f);
}

fn main() {
}

@compute
fn main() {
}
