// Generated by WebGPU-KTypes WGSL Backend
struct Struct_9 {
    vec4f: vec4<f32>,
    vec4i: vec4<i32>,
    vec4u: vec4<u32>,
    vec3f: vec3<f32>,
    vec3i: vec3<i32>,
    vec3u: vec3<u32>,
}
struct Struct_13 {
    vec2f: vec2<f32>,
    vec2i: vec2<i32>,
    vec2u: vec2<u32>,
    scalarf: f32,
    scalari: i32,
    scalaru: u32,
}

fn main_vec4vec3() -> Struct_9 {
    Struct_9 local_0;
    local_0.vec4f = vec4<f32>(0.0f);
    local_0.vec4i = vec4<f32>(0);
    local_0.vec4u = vec4<f32>(0u);
    local_0.vec3f = vec3<f32>(0.0f);
    local_0.vec3i = vec3<f32>(0);
    local_0.vec3u = vec3<f32>(0u);
    return local_0;
}

fn main_vec2scalar() -> Struct_13 {
    Struct_13 local_0;
    local_0.vec2f = vec2<f32>(0.0f);
    local_0.vec2i = vec2<f32>(0);
    local_0.vec2u = vec2<f32>(0u);
    local_0.scalarf = 0.0f;
    local_0.scalari = 0;
    local_0.scalaru = 0u;
    return local_0;
}

@fragment
fn main_vec4vec3() -> Struct_9 {
}

@fragment
fn main_vec2scalar() -> Struct_13 {
}
