// Generated by WebGPU-KTypes WGSL Backend
struct Struct_11 {
    val_u32: u32,
    val_i32: i32,
    val_f32: f32,
    val_u64: u64,
    val_u64_2: vec2<u64>,
    val_u64_3: vec3<u64>,
    val_u64_4: vec4<u64>,
    val_i64: i64,
    val_i64_2: vec2<i64>,
    val_i64_3: vec3<i64>,
    val_i64_4: vec4<i64>,
    final_value: u64,
}
struct Struct_14 {
    val_u64_array_2: array<u64, 2>,
    val_i64_array_2: array<i64, 2>,
}
var<private> private_variable: i64 = 1;
var<private> constant_variable: u64 = 20u;
@group(0) @binding(0)
var<uniform> input_uniform: Struct_11;
@group(0) @binding(1)
var<storage> input_storage: Struct_11;
@group(0) @binding(3)
var<storage, read_write> output: Struct_11;
@group(0) @binding(2)
var<storage> input_arrays: Struct_14;
@group(0) @binding(4)
var<storage, read_write> output_arrays: Struct_14;

fn int64_function(x: i64) -> i64 {
    _ = private_variable;
    var val: i64 = i64(constant_variable);
    val = ((31 - 1002003004005006) + -(7));
    val = (val + i64(5));
    val = i64((input_uniform.val_u32 + u32(val)));
    val = i64((input_uniform.val_i32 + i32(val)));
    val = i64((input_uniform.val_f32 + f32(val)));
    val = vec3<i64>(input_uniform.val_i64)[2];
    val = bitcast<i64>(input_uniform.val_u64);
    val = bitcast<vec2<i64>>(input_uniform.val_u64_2)[1];
    val = bitcast<vec3<i64>>(input_uniform.val_u64_3)[2];
    val = bitcast<vec4<i64>>(input_uniform.val_u64_4)[3];
    val = i64((-(-1) - 1));
    output.val_i64 = (input_uniform.val_i64 + input_storage.val_i64);
    output.val_i64_2 = (input_uniform.val_i64_2 + input_storage.val_i64_2);
    output.val_i64_3 = (input_uniform.val_i64_3 + input_storage.val_i64_3);
    output.val_i64_4 = (input_uniform.val_i64_4 + input_storage.val_i64_4);
    output_arrays.val_i64_array_2 = input_arrays.val_i64_array_2;
    val = abs(val);
    val = clamp(val, val, val);
    val = dot(vec2<f32>(val), vec2<f32>(val));
    val = max(val, val);
    val = min(val, val);
    val = sign(val);
    return val;
}

fn abs(arg_0: i64) -> i64 {
}

fn clamp(arg_0: i64, arg_1: i64, arg_2: i64) -> i64 {
}

fn dot(arg_0: vec2<f32>, arg_1: vec2<f32>) -> vec2<f32> {
}

fn max(arg_0: i64, arg_1: i64) -> i64 {
}

fn min(arg_0: i64, arg_1: i64) -> i64 {
}

fn sign(arg_0: i64) -> i64 {
}

fn uint64_function(x: u64) -> u64 {
    var val: u64 = u64(constant_variable);
    val = ((31u + 0u) - 0);
    val = (val + u64(5));
    val = u64((input_uniform.val_u32 + u32(val)));
    val = u64((input_uniform.val_i32 + i32(val)));
    val = u64((input_uniform.val_f32 + f32(val)));
    val = vec3<u64>(input_uniform.val_u64)[2];
    val = bitcast<u64>(input_uniform.val_i64);
    val = bitcast<vec2<u64>>(input_uniform.val_i64_2)[1];
    val = bitcast<vec3<u64>>(input_uniform.val_i64_3)[2];
    val = bitcast<vec4<u64>>(input_uniform.val_i64_4)[3];
    output.val_u64 = (input_uniform.val_u64 + input_storage.val_u64);
    output.val_u64_2 = (input_uniform.val_u64_2 + input_storage.val_u64_2);
    output.val_u64_3 = (input_uniform.val_u64_3 + input_storage.val_u64_3);
    output.val_u64_4 = (input_uniform.val_u64_4 + input_storage.val_u64_4);
    output_arrays.val_u64_array_2 = input_arrays.val_u64_array_2;
    val = abs(val);
    val = clamp(val, val, val);
    val = dot(vec2<f32>(val), vec2<f32>(val));
    val = max(val, val);
    val = min(val, val);
    return val;
}

fn abs(arg_0: u64) -> u64 {
}

fn clamp(arg_0: u64, arg_1: u64, arg_2: u64) -> u64 {
}

fn dot(arg_0: vec2<f32>, arg_1: vec2<f32>) -> vec2<f32> {
}

fn max(arg_0: u64, arg_1: u64) -> u64 {
}

fn min(arg_0: u64, arg_1: u64) -> u64 {
}

@compute
fn main() {
    output.final_value = (uint64_function(67u) + bitcast<u64>(int64_function(60)));
}
