// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    position: vec4<f32>,
    _varying: f32,
}
struct Struct_4 {
    depth: f32,
    sample_mask: u32,
    color: f32,
}
struct Struct_5 {
    index: u32,
}
var<workgroup> output: array<u32>;

@vertex
fn vertex_two_structs(in1: Struct_5, in2: Struct_5) -> vec4<f32> {
    var index: u32 = 0u;
    return vec4<f32>(f32(in1.index), f32(in2.index), f32(index), 0.0f);
}
