// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    a: i32,
    b: mat2x2<f32>,
}
@group(0) @binding(0)
var<uniform> global_0: Struct_3;

fn main() {
    Struct_3 local_0 = global_0;
}

@compute
fn main() {
}
