// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    values: /* unknown type */,
}
var<storage, read_write> global_0: Struct_2;
var<storage, read_write> global_1: Struct_2;

fn main() {
    global_0.values[0] = global_1.values[0];
}

@compute
fn main() {
}
