// Generated by WebGPU-KTypes WGSL Backend
struct Struct_1 {
    x: i32,
}
var<private> Value: i32 = 1;
@group(0) @binding(0)
var<private> Texture: texture_2d<f32>;
@group(0) @binding(1)
var<private> Sampler: sampler;

fn statement() {
}

fn returns() -> Struct_1 {
    return Struct_1(Value);
}

fn call() {
    var x: Struct_1 = returns();
    var vf: f32 = f32(Value);
    var s: texture_2d<f32> = textureSample(Texture, Sampler, vec2<f32>(vf));
}

fn textureSample() {
}

@fragment
fn main() {
}
