// Generated by WebGPU-KTypes WGSL Backend

fn use_me() -> i32 {
    return 10;
}

fn use_return() -> i32 {
    return use_me();
}

fn use_assign_var() -> i32 {
    f32 local_0 = use_me();
    return local_0;
}

fn use_assign_let() -> i32 {
    f32 local_0 = use_me();
    return local_0;
}

fn use_phony_assign() {
}

fn main() {
}

@compute
fn main() {
}
