// Generated by WebGPU-KTypes WGSL Backend
var<private> o: i32;
var<workgroup> a: u32;

fn atomicCompareExchangeWeak(arg_0: ptr<function, u32>, arg_1: u32, arg_2: u32) -> ptr<function, u32> {
}

@compute
fn f() {
}
