// Generated by WebGPU-KTypes WGSL Backend
struct Struct_4 {
    old_value: u32,
    exchanged: bool,
}
var<private> o: i32;
var<workgroup> a: u32;

fn atomicCompareExchangeWeak(arg_0: ptr<function, u32>, arg_1: u32, arg_2: u32) -> Struct_4 {
}

@compute
fn f() {
    atomicCompareExchangeWeak(&a, u32(o), 1u);
}
