// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<uniform> binding: f32;

fn five() -> i32 {
    return 5;
}

@compute
fn main(id: vec3<u32>) {
    var a: i32 = 5;
    var b: i32 = five();
    var phony: f32 = binding;
}
