// Generated by WebGPU-KTypes WGSL Backend

fn takes_ptr(p: ptr<function, i32>) {
}

fn takes_array_ptr(p: ptr<function, array<i32, 4>>) {
}

fn takes_vec_ptr(p: ptr<function, vec2<i32>>) {
}

fn takes_mat_ptr(p: ptr<function, mat2x2<f32>>) {
}

fn argument(v: ptr<function, array<i32, 4>>, i: u32) {
}

fn argument_nested_x3(v: ptr<function, array<array<array<i32, 4>, 4>, 4>>, i: u32, j: u32) {
}

fn index_from_self(v: ptr<function, array<i32, 4>>, i: u32) {
}

fn local_var_from_arg(a: array<i32, 4>, i: u32) {
    var b: array<i32, 4> = a;
}

fn let_binding(a: ptr<function, array<i32, 4>>, i: u32) {
    var p0: ptr<function, ptr<function, i32>> = &a[i];
    var p1: ptr<function, ptr<function, i32>> = &a[0];
}

fn local_var(i: u32) {
    var arr: array<i32, 4> = array<i32, 4>(1, 2, 3, 4);
}

fn argument_nested_x2(v: ptr<function, array<array<i32, 4>, 4>>, i: u32, j: u32) {
}

fn mat_vec_ptrs(pv: ptr<function, array<vec2<i32>, 4>>, pm: ptr<function, array<mat2x2<f32>, 4>>, i: u32) {
}

@compute
fn main() {
    var vec: array<vec2<i32>, 4>;
    var mat: array<mat2x2<f32>, 4>;
    var arr1d: array<i32, 4>;
    var arr2d: array<array<i32, 4>, 4>;
    var arr3d: array<array<array<i32, 4>, 4>, 4>;
}
