// Generated by WebGPU-KTypes WGSL Backend
struct Struct_1 {
    hit_num: u32,
    selected_hit: u32,
}
@group(0) @binding(0)
var<private> acc_struct: acceleration_structure;
var<private> hit_num: Struct_1;
var<private> incoming_hit_num: Struct_1;

fn miss(origin: vec3<f32>, dir: vec3<f32>, t_min: f32) {
}

fn closest_hit_main(origin: vec3<f32>, dir: vec3<f32>, obj_to_world: mat4x3<f32>, world_to_obj: mat4x3<f32>) {
}

fn ray_gen_main(id: vec3<u32>, num_invocations: vec3<u32>) {
    hit_num = Struct_1();
    var shift: vec3<f32> = (vec3<f32>(id) / vec3<f32>(num_invocations));
    var ray_shift: vec3<f32> = ((vec3<f32>(shift[0], 0.0f, shift[1]) * 2.0f) - 1.0f);
}

fn traceRay() {
}

fn RayDesc() {
}

fn any_hit_main(data: u32, geo_idx: u32, max: f32, kind: u32) {
    incoming_hit_num.hit_num = (incoming_hit_num.hit_num + 1);
    incoming_hit_num.selected_hit = data;
}
