// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> t1: f32;
@group(0) @binding(1)
var<private> t2: f32;
@group(0) @binding(2)
var<private> s1: f32;
@group(0) @binding(3)
var<private> s2: f32;
@group(0) @binding(4)
var<uniform> uniformOne: vec2<f32>;
@group(1) @binding(0)
var<uniform> uniformTwo: vec2<f32>;

fn textureSample() {
}

fn textureSample() {
}

fn textureSample() {
}

fn textureSample() {
}

@fragment
fn entry_point_one(@builtin(position) pos: vec4<f32>) -> vec4<f32> {
    return textureSample(t1, s1, pos.xy);
}

@fragment
fn entry_point_two() -> vec4<f32> {
    return textureSample(t1, s1, uniformOne);
}

@fragment
fn entry_point_three() -> vec4<f32> {
    return (textureSample(t1, s1, (uniformTwo + uniformOne)) + textureSample(t2, s2, uniformOne));
}
