// Generated by WebGPU-KTypes WGSL Backend

fn select() {
}

fn select() {
}

@compute
fn main() {
    var x0: vec2<f32> = vec2<f32>(1, 2);
    var i1: vec2<f32> = select(vec2<f32>(1.0f, 0.0f), vec2<f32>(0.0f, 1.0f), (x0[0] < x0[1]));
}
