// Generated by WebGPU-KTypes WGSL Backend

fn derivatives() {
    var x: f32 = dpdx(0.0f);
    var y: f32 = dpdy(0.0f);
    var width: f32 = fwidth(0.0f);
}

fn dpdx() {
}

fn dpdy() {
}

fn fwidth() {
}

fn barriers() {
}

fn storageBarrier() {
}

fn workgroupBarrier() {
}

fn textureBarrier() {
}

@fragment
fn fragment() -> vec4<f32> {
    return vec4<f32>();
}

@compute
fn compute() {
}
