// Generated by WebGPU-KTypes WGSL Backend

fn derivatives() {
    var x: f32 = dpdx(0.0f);
    var y: f32 = dpdy(0.0f);
    var width: f32 = fwidth(0.0f);
}

fn dpdx(arg_0: f32) -> f32 {
}

fn dpdy(arg_0: f32) -> f32 {
}

fn fwidth(arg_0: f32) -> f32 {
}

fn barriers() {
    storageBarrier();
    workgroupBarrier();
    textureBarrier();
}

fn storageBarrier() {
}

fn workgroupBarrier() {
}

fn textureBarrier() {
}

@fragment
fn fragment() -> vec4<f32> {
    derivatives();
    return vec4<f32>();
}

@compute
fn compute() {
    barriers();
}
