// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> u_texture: f32;
@group(0) @binding(1)
var<private> u_sampler: f32;

fn textureSample() {
}

@fragment
fn main(@location(0) uv: vec2<f32>) -> vec4<f32> {
    return textureSample(u_texture, u_sampler, uv);
}
