// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> u_texture: texture_2d<f32>;
@group(0) @binding(1)
var<private> u_sampler: sampler;

fn textureSample(arg_0: texture_2d<f32>, arg_1: sampler, arg_2: vec2<f32>) -> texture_2d<f32> {
}

@fragment
fn main(@location(0) uv: vec2<f32>) -> vec4<f32> {
    return textureSample(u_texture, u_sampler, uv);
}
