// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> s_r_r: texture_storage_2d<r32float, read>;
@group(0) @binding(1)
var<private> s_rg_r: texture_storage_2d<rg32float, read>;
@group(0) @binding(2)
var<private> s_rgba_r: texture_storage_2d<rgba32float, read>;
@group(1) @binding(0)
var<private> s_r_w: texture_storage_2d<r32float, write>;
@group(1) @binding(1)
var<private> s_rg_w: texture_storage_2d<rg32float, write>;
@group(1) @binding(2)
var<private> s_rgba_w: texture_storage_2d<rgba32float, write>;

fn textureLoad() {
}

fn textureLoad() {
}

fn textureLoad() {
}

fn textureStore() {
}

fn textureStore() {
}

fn textureStore() {
}

@compute
fn csLoad() {
}

@compute
fn csStore() {
}
