// Generated by WebGPU-KTypes WGSL Backend
struct Struct_1 {
    num_subgroups: u32,
    subgroup_size: u32,
}

fn subgroupBallot() {
}

fn subgroupBallot() {
}

fn subgroupAll() {
}

fn subgroupAny() {
}

fn subgroupAdd() {
}

fn subgroupMul() {
}

fn subgroupMin() {
}

fn subgroupMax() {
}

fn subgroupAnd() {
}

fn subgroupOr() {
}

fn subgroupXor() {
}

fn subgroupExclusiveAdd() {
}

fn subgroupExclusiveMul() {
}

fn subgroupInclusiveAdd() {
}

fn subgroupInclusiveMul() {
}

fn subgroupBroadcastFirst() {
}

fn subgroupBroadcast() {
}

fn subgroupShuffle() {
}

fn subgroupShuffleDown() {
}

fn subgroupShuffleUp() {
}

fn subgroupShuffleXor() {
}

fn quadBroadcast() {
}

fn quadSwapX() {
}

fn quadSwapY() {
}

fn quadSwapDiagonal() {
}

@compute
fn main(sizes: Struct_1, subgroup_id: u32, subgroup_invocation_id: u32) {
}
