// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> Texture: f32;
@group(0) @binding(1)
var<private> Sampler: f32;

fn test(Passed_Texture: f32, Passed_Sampler: f32) -> vec4<f32> {
    return textureSample(Passed_Texture, Passed_Sampler, vec2<f32>(0.0f, 0.0f));
}

fn textureSample() {
}

@fragment
fn main() -> vec4<f32> {
    return test(Texture, Sampler);
}
