// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> tex: f32;
@group(0) @binding(1)
var<private> samp: f32;

fn test(t: f32) -> vec4<f32> {
    var a: f32 = textureSampleBaseClampToEdge(t, samp, vec2<f32>(0.0f));
    var b: f32 = textureLoad(t, vec2<f32>(0));
    var c: f32 = textureLoad(t, vec2<f32>(0u));
    var d: f32 = textureDimensions(t);
    return (((a + b) + c) + vec2<f32>(d).xyxy);
}

fn textureSampleBaseClampToEdge() {
}

fn textureLoad() {
}

fn textureLoad() {
}

fn textureDimensions() {
}

@fragment
fn fragment_main() -> vec4<f32> {
    return test(tex);
}

@vertex
fn vertex_main() -> vec4<f32> {
    return test(tex);
}

@compute
fn compute_main() {
}
