// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> Texture: texture_2d<f32>;
@group(0) @binding(1)
var<private> Sampler: sampler;

fn test(Passed_Texture: texture_2d<f32>, Passed_Sampler: sampler) -> vec4<f32> {
    return textureSample(Passed_Texture, Passed_Sampler, vec2<f32>(0.0f, 0.0f));
}

fn textureSample(arg_0: texture_2d<f32>, arg_1: sampler, arg_2: vec2<f32>) -> vec4<f32> {
}

@fragment
fn main() -> vec4<f32> {
    return test(Texture, Sampler);
}
