// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> tex: texture_external;
@group(0) @binding(1)
var<private> samp: sampler;

fn test(t: texture_external) -> vec4<f32> {
    var a: texture_external = textureSampleBaseClampToEdge(t, samp, vec2<f32>(0.0f));
    var b: texture_external = textureLoad(t, vec2<f32>(0));
    var c: texture_external = textureLoad(t, vec2<f32>(0u));
    var d: texture_external = textureDimensions(t);
    return (((a + b) + c) + vec2<f32>(d).xyxy);
}

fn textureSampleBaseClampToEdge() {
}

fn textureLoad() {
}

fn textureLoad() {
}

fn textureDimensions() {
}

@fragment
fn fragment_main() -> vec4<f32> {
    return test(tex);
}

@vertex
fn vertex_main() -> vec4<f32> {
    return test(tex);
}

@compute
fn compute_main() {
}
