// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> tex: texture_external;
@group(0) @binding(1)
var<private> samp: sampler;

fn test(t: texture_external) -> vec4<f32> {
    var a: vec4<f32> = textureSampleBaseClampToEdge(t, samp, vec2<f32>(0.0f));
    var b: texture_external = textureLoad(t, vec2<f32>(0));
    var c: texture_external = textureLoad(t, vec2<f32>(0u));
    var d: vec2<u32> = textureDimensions(t);
    return (((a + b) + c) + vec2<f32>(d).xyxy);
}

fn textureSampleBaseClampToEdge(arg_0: texture_external, arg_1: sampler, arg_2: vec2<f32>) -> vec4<f32> {
}

fn textureLoad(arg_0: texture_external, arg_1: vec2<f32>) -> texture_external {
}

fn textureLoad(arg_0: texture_external, arg_1: vec2<f32>) -> texture_external {
}

fn textureDimensions(arg_0: texture_external) -> vec2<u32> {
}

@fragment
fn fragment_main() -> vec4<f32> {
    return test(tex);
}

@vertex
fn vertex_main() -> vec4<f32> {
    return test(tex);
}

@compute
fn compute_main() {
    test(tex);
}
