// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<private> texture: texture_depth_2d_array;
@group(0) @binding(1)
var<private> texture_sampler: sampler_comparison;

fn textureSampleCompareLevel(arg_0: texture_depth_2d_array, arg_1: sampler_comparison, arg_2: vec2<f32>, arg_3: i32, arg_4: f32) -> texture_depth_2d_array {
}

@fragment
fn main() -> f32 {
    var pos: vec2<f32> = vec2<f32>(0.0f);
    var array_index: i32 = 0;
    var depth: f32 = 0.0f;
    return textureSampleCompareLevel(texture, texture_sampler, pos, array_index, depth);
}
