// Generated by WebGPU-KTypes WGSL Backend
struct Struct_5 {
    arr: array<u32, 512>,
    atom: i32,
    atom_arr: array<array<i32, 8>, 8>,
}
@group(0) @binding(0)
var<storage, read_write> output: array<u32, 512>;
var<workgroup> w_mem: Struct_5;

@compute
fn main() {
    output = w_mem.arr;
}
