// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    atomic_scalar: u32,
    atomic_arr: array<i32, 2>,
}
var<workgroup> wg_scalar: u32;
var<workgroup> wg_signed: i32;
var<workgroup> wg_struct: Struct_3;

fn atomicOr(arg_0: ptr<function, u32>, arg_1: u32) -> ptr<function, u32> {
}

fn atomicAdd(arg_0: ptr<function, i32>, arg_1: i32) -> ptr<function, i32> {
}

fn atomicStore(arg_0: ptr<function, u32>, arg_1: u32) -> ptr<function, u32> {
}

fn atomicAdd(arg_0: ptr<function, i32>, arg_1: i32) -> ptr<function, i32> {
}

fn workgroupBarrier() {
}

fn workgroupUniformLoad(arg_0: ptr<function, u32>) -> ptr<function, u32> {
}

fn workgroupUniformLoad(arg_0: ptr<function, i32>) -> ptr<function, i32> {
}

fn workgroupUniformLoad(arg_0: ptr<function, u32>) -> ptr<function, u32> {
}

fn workgroupUniformLoad(arg_0: ptr<function, i32>) -> ptr<function, i32> {
}

@compute
fn test_atomic_workgroup_uniform_load(workgroup_id: vec3<u32>, local_id: vec3<u32>) {
    var active_tile_index: u32 = (workgroup_id[0] + (workgroup_id[1] * 32768));
    atomicOr(&wg_scalar, u32((active_tile_index >= 64)));
    atomicAdd(&wg_signed, 1);
    atomicStore(&wg_struct.atomic_scalar, 1u);
    atomicAdd(&wg_struct.atomic_arr[0], 1);
    workgroupBarrier();
    var scalar_val: u32 = workgroupUniformLoad(&wg_scalar);
    var signed_val: i32 = workgroupUniformLoad(&wg_signed);
    var struct_scalar: u32 = workgroupUniformLoad(&wg_struct.atomic_scalar);
    var struct_arr_val: i32 = workgroupUniformLoad(&wg_struct.atomic_arr[0]);
    if (((((scalar_val == 0u) && (signed_val > 0)) && (struct_scalar > 0u)) && (struct_arr_val > 0))) {
        return;
    }
}
