// Generated by WebGPU-KTypes WGSL Backend
struct Struct_5 {
    arr: /* unknown type */,
    atom: f32,
    atom_arr: /* unknown type */,
}
var<storage, read_write> global_0: /* unknown type */;
var<workgroup> global_1: Struct_5;

fn main() {
    global_0 = global_1.arr;
}

@compute
fn main() {
}
