// Generated by WebGPU-KTypes WGSL Backend
var<private> SIZE: u32 = 128u;
var<workgroup> arr_i32: array<i32>;

fn workgroupUniformLoad(arg_0: ptr<function, i32>) -> ptr<function, i32> {
}

fn workgroupBarrier() {
}

@compute
fn test_workgroupUniformLoad(workgroup_id: vec3<u32>) {
    var x: ptr<function, i32> = &arr_i32[workgroup_id[0]];
    var val: ptr<function, i32> = workgroupUniformLoad(x);
    if ((val > 10)) {
        workgroupBarrier();
    }
}
