package io.ygdrasil.wgsl.wgsl

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.string.shouldContain
import io.ygdrasil.wgsl.arena.rangeOf
import io.ygdrasil.wgsl.arena.Arena
import io.ygdrasil.wgsl.ir.BindingAttribute
import io.ygdrasil.wgsl.ir.Block
import io.ygdrasil.wgsl.ir.BuiltinValue
import io.ygdrasil.wgsl.ir.Expression
import io.ygdrasil.wgsl.ir.ExpressionKind
import io.ygdrasil.wgsl.ir.Function
import io.ygdrasil.wgsl.ir.LiteralValue
import io.ygdrasil.wgsl.ir.Module
import io.ygdrasil.wgsl.ir.ScalarKind
import io.ygdrasil.wgsl.ir.ScalarValue
import io.ygdrasil.wgsl.ir.Statement
import io.ygdrasil.wgsl.ir.StructMember
import io.ygdrasil.wgsl.ir.Type
import io.ygdrasil.wgsl.ir.TypeInner
import io.ygdrasil.wgsl.ir.UnaryOperator

class WgslWriterTest : FunSpec({

    test("testEmptyModule") {
        val module = Module()
        val code = WgslModule.writeString(module)
        code shouldContain "// Generated by WebGPU-KTypes WGSL Backend"
    }

    test("testModuleWithStructAndFunction") {
        val module = Module()

        // Add a scalar type
        val f32Handle = module.types.append(Type(TypeInner.Scalar(ScalarKind.F32, 4)))

        // Add a struct
        module.types.append(
            Type(
                TypeInner.Struct(
                    listOf(
                        StructMember("a", f32Handle, null, 0)
                    )
                )
            )
        )

        // Add a function
        val expressions = Arena<Expression>()
        val blocks = Arena<Block>()
        val body = blocks.append(Block(emptyList()))

        module.functions.append(
            Function(
                name = "my_func",
                parameters = emptyList(),
                returnType = null,
                localVariables = Arena(),
                expressions = expressions,
                blocks = blocks,
                body = body
            )
        )

        val code = WgslModule.writeString(module)
        code shouldContain "struct Struct_1"
        code shouldContain "a: f32"
        code shouldContain "fn my_func()"
    }

    test("struct member builtin bindings are written") {
        val module = Module()
        val u32Handle = module.types.append(Type(TypeInner.Scalar(ScalarKind.Uint, 4)))

        module.types.append(
            Type(
                TypeInner.Struct(
                    listOf(
                        StructMember("draw_index", u32Handle, BindingAttribute.Builtin(BuiltinValue.DrawIndex), 0)
                    )
                )
            )
        )

        val code = WgslModule.writeString(module)
        code shouldContain "@builtin(draw_index) draw_index: u32"
    }

    test("emit non call expression writes phony assignment") {
        val module = Module()
        val expressions = Arena<Expression>()
        val expression = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.I32(1))))
        )
        val blocks = Arena<Block>()
        val body = blocks.append(Block(listOf(Statement.Emit(rangeOf(expression)))))

        module.functions.append(
            Function(
                name = "main",
                parameters = emptyList(),
                returnType = null,
                localVariables = Arena(),
                expressions = expressions,
                blocks = blocks,
                body = body
            )
        )

        val code = WgslModule.writeString(module)
        code shouldContain "_ = 1;"
    }

    test("non-finite float literals do not get numeric decimal suffixes") {
        val module = Module()
        val expressions = Arena<Expression>()
        val infinity = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.F32(Float.POSITIVE_INFINITY))))
        )
        val negativeInfinity = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.F32(Float.NEGATIVE_INFINITY))))
        )
        val nan = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.F32(Float.NaN))))
        )
        val blocks = Arena<Block>()
        val body = blocks.append(
            Block(
                listOf(
                    Statement.Emit(rangeOf(infinity)),
                    Statement.Emit(rangeOf(negativeInfinity)),
                    Statement.Emit(rangeOf(nan))
                )
            )
        )

        module.functions.append(
            Function(
                name = "main",
                parameters = emptyList(),
                returnType = null,
                localVariables = Arena(),
                expressions = expressions,
                blocks = blocks,
                body = body
            )
        )

        val code = WgslModule.writeString(module)
        code shouldContain "_ = Infinityf;"
        code shouldContain "_ = -Infinityf;"
        code shouldContain "_ = NaNf;"
    }

    test("negated negative integer literals are written with stable roundtrip shape") {
        val module = Module()
        val expressions = Arena<Expression>()
        val minI32 = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.I32(Int.MIN_VALUE))))
        )
        val negativeI32 = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.I32(-5))))
        )
        val negated = expressions.append(Expression(ExpressionKind.Unary(UnaryOperator.Negate, minI32)))
        val negatedNegative = expressions.append(Expression(ExpressionKind.Unary(UnaryOperator.Negate, negativeI32)))
        val blocks = Arena<Block>()
        val body = blocks.append(Block(listOf(Statement.Emit(rangeOf(negated)), Statement.Emit(rangeOf(negatedNegative)))))

        module.functions.append(
            Function(
                name = "main",
                parameters = emptyList(),
                returnType = null,
                localVariables = Arena(),
                expressions = expressions,
                blocks = blocks,
                body = body
            )
        )

        val code = WgslModule.writeString(module)
        code shouldContain "_ = -(2147483648);"
        code shouldContain "_ = -(-5);"
    }
})
