// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    uint3 local_invocation_id;
    uint local_invocation_index;
};
uint global_0;

[numthreads(1, 1, 1)]
void compute1() {
}
