// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


struct func_Input {
    float input_location : TEXCOORD0;
    float4 arbitrary_position : SV_Position;
};
struct func_Output {
    float4 color : SV_Target;
};
func_Output func(func_Input stage_in) {
    func_Output stage_out;
    float input_location = stage_in.input_location;
    float4 arbitrary_position = stage_in.arbitrary_position;
    return stage_out;
}
