// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    float f;
    int i;
    uint u;
};
int2 global_0 = float2(42, 43);
uint2 global_1 = float2(44, 45);
float2 global_2 = float2(46, 47);
float2 global_3 = float2(48.0f, 49.0f);
float2 global_4 = float2(48, 49.0f);
uint2 global_5 = float2(0u, 43);
uint2 global_6 = float2(42, 0u);
uint2 global_7 = uint2(0u, 43);
uint2 global_8 = uint2(42, 0u);
int2 global_9 = float2();
uint2 global_10 = float2();
float2 global_11 = float2();
float2x2 global_12 = float2x2(float2(), float2());
float2x2 global_13 = float2x2(1, 2, 3, 4);
float2x2 global_14 = float2x2(1.0f, 2, 3, 4);
float2x2 global_15 = float2x2(1, 2.0f, 3, 4);
float2x2 global_16 = float2x2(1, 2, 3.0f, 4);
float2x2 global_17 = float2x2(1, 2, 3, 4.0f);
void global_18 = void(1, 2);
void global_19 = void(1, 2);
void global_20 = void(1, 2.0f);
void global_21 = void(1.0f, 2);
void global_22 = void(1.0f, 2.0f);
int2 global_23 = float2(1);
uint2 global_24 = float2(1);
float2 global_25 = float2(1);
float2 global_26 = float2(1.0f);
Struct_3 global_27 = Struct_3(1.0f, 0, 0u);
Struct_3 global_28 = Struct_3(1.0f, 0, 1);
Struct_3 global_29 = Struct_3(1.0f, 1, 0u);
Struct_3 global_30 = Struct_3(1.0f, 1, 1);
Struct_3 global_31 = Struct_3(1.0f, 0, 0u);
Struct_3 global_32 = Struct_3(1.0f, 0, 1);
Struct_3 global_33 = Struct_3(1.0f, 1, 0u);
Struct_3 global_34 = Struct_3(1.0f, 1, 1);
