// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


[numthreads(1, 1, 1)]
void f() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void clamp() {
}

void min() {
}

void min() {
}

void min() {
}

void min() {
}

void min() {
}

void min() {
}

void min() {
}

void min() {
}

void min() {
}

void min() {
}

void min() {
}

void min() {
}

void pow() {
}

void pow() {
}

void pow() {
}

void pow() {
}

void pow() {
}

void pow() {
}

void pow() {
}

void pow() {
}

void pow() {
}
