// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

int global_0 : register(u0);
uint global_1 : register(u1);

void test_atomic_i32() {
}

void atomicStore() {
}

void atomicCompareExchangeWeak() {
}

void atomicCompareExchangeWeak() {
}

void atomicAdd() {
}

void atomicSub() {
}

void atomicAnd() {
}

void atomicXor() {
}

void atomicOr() {
}

void atomicMin() {
}

void atomicMax() {
}

void atomicExchange() {
}

void test_atomic_u32() {
}

void atomicStore() {
}

void atomicCompareExchangeWeak() {
}

void atomicCompareExchangeWeak() {
}

void atomicAdd() {
}

void atomicSub() {
}

void atomicAnd() {
}

void atomicXor() {
}

void atomicOr() {
}

void atomicMin() {
}

void atomicMax() {
}

void atomicExchange() {
}

[numthreads(1, 1, 1)]
void main() {
}
