// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

float global_0 : register(t0);
float global_1 : register(t1);
float global_2 : register(t2);
float global_3 : register(t3);
float global_4 : register(t4);

void color() {
}

void textureSample() {
}

void textureSample() {
}

void textureSampleLevel() {
}

void textureSampleLevel() {
}

void textureSampleGrad() {
}

void textureSampleBias() {
}

void depth() {
}

void textureSampleLevel() {
}

void textureSampleCompare() {
}

void textureGatherCompare() {
}

void main() {
}

void () {
}
