// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


void ret_array() {
    return void(1.0f, 2.0f);
}

void ret_array_array() {
    return void(ret_array(), ret_array(), ret_array());
}

struct main_Output {
    float4 color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    return stage_out;
}
