// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

texture_storage_2d<r32uint> global_0 : register(t0);
texture_storage_2d<r32sint> global_1 : register(t1);

[numthreads(1, 1, 1)]
void cs_main() {
    textureAtomicMax(global_0, int2(0, 0), 1u);
    textureAtomicMin(global_0, int2(0, 0), 1u);
    textureAtomicAdd(global_0, int2(0, 0), 1u);
    textureAtomicAnd(global_0, int2(0, 0), 1u);
    textureAtomicOr(global_0, int2(0, 0), 1u);
    textureAtomicXor(global_0, int2(0, 0), 1u);
    textureAtomicMax(global_1, int2(0, 0), 1);
    textureAtomicMin(global_1, int2(0, 0), 1);
    textureAtomicAdd(global_1, int2(0, 0), 1);
    textureAtomicAnd(global_1, int2(0, 0), 1);
    textureAtomicOr(global_1, int2(0, 0), 1);
    textureAtomicXor(global_1, int2(0, 0), 1);
}

texture_storage_2d<r32uint> textureAtomicMax(texture_storage_2d<r32uint> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32uint> textureAtomicMin(texture_storage_2d<r32uint> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32uint> textureAtomicAdd(texture_storage_2d<r32uint> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32uint> textureAtomicAnd(texture_storage_2d<r32uint> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32uint> textureAtomicOr(texture_storage_2d<r32uint> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32uint> textureAtomicXor(texture_storage_2d<r32uint> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32sint> textureAtomicMax(texture_storage_2d<r32sint> arg_0, int2 arg_1, int arg_2) {
}

texture_storage_2d<r32sint> textureAtomicMin(texture_storage_2d<r32sint> arg_0, int2 arg_1, int arg_2) {
}

texture_storage_2d<r32sint> textureAtomicAdd(texture_storage_2d<r32sint> arg_0, int2 arg_1, int arg_2) {
}

texture_storage_2d<r32sint> textureAtomicAnd(texture_storage_2d<r32sint> arg_0, int2 arg_1, int arg_2) {
}

texture_storage_2d<r32sint> textureAtomicOr(texture_storage_2d<r32sint> arg_0, int2 arg_1, int arg_2) {
}

texture_storage_2d<r32sint> textureAtomicXor(texture_storage_2d<r32sint> arg_0, int2 arg_1, int arg_2) {
}
