// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float atomic_scalar;
    void atomic_arr;
};
float global_0 : register(u0);
void global_1 : register(u1);
Struct_2 global_2 : register(u2);

[numthreads(1, 1, 1)]
void cs_main() {
}

void atomicStore() {
}

void atomicStore() {
}

void atomicStore() {
}

void atomicStore() {
}

void workgroupBarrier() {
}

void atomicLoad() {
}

void atomicLoad() {
}

void atomicLoad() {
}

void atomicLoad() {
}

void workgroupBarrier() {
}

void atomicAdd() {
}

void atomicAdd() {
}

void atomicAdd() {
}

void atomicAdd() {
}

void workgroupBarrier() {
}

void atomicExchange() {
}

void atomicExchange() {
}

void atomicExchange() {
}

void atomicExchange() {
}
