// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

texture_storage_2d<r64uint> global_0 : register(t0);

[numthreads(1, 1, 1)]
void cs_main() {
    textureAtomicMax(global_0, int2(0, 0), 1u);
    workgroupBarrier();
    textureAtomicMin(global_0, int2(0, 0), 1u);
}

texture_storage_2d<r64uint> textureAtomicMax(texture_storage_2d<r64uint> arg_0, int2 arg_1, uint64_t arg_2) {
}

void workgroupBarrier() {
}

texture_storage_2d<r64uint> textureAtomicMin(texture_storage_2d<r64uint> arg_0, int2 arg_1, uint64_t arg_2) {
}
