// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    uint atomic_scalar;
    void atomic_arr;
};
uint global_0 : register(u0);
void global_1 : register(u1);
uint global_2;
void global_3;
Struct_3 global_4 : register(u2);
Struct_3 global_5;

[numthreads(1, 1, 1)]
void cs_main() {
}

void atomicStore() {
}

void atomicStore() {
}

void atomicStore() {
}

void atomicStore() {
}

void atomicStore() {
}

void atomicStore() {
}

void atomicStore() {
}

void atomicStore() {
}

void workgroupBarrier() {
}

void atomicLoad() {
}

void atomicLoad() {
}

void atomicLoad() {
}

void atomicLoad() {
}

void atomicLoad() {
}

void atomicLoad() {
}

void atomicLoad() {
}

void atomicLoad() {
}

void workgroupBarrier() {
}

void atomicAdd() {
}

void atomicAdd() {
}

void atomicAdd() {
}

void atomicAdd() {
}

void atomicAdd() {
}

void atomicAdd() {
}

void atomicAdd() {
}

void atomicAdd() {
}

void workgroupBarrier() {
}

void atomicSub() {
}

void atomicSub() {
}

void atomicSub() {
}

void atomicSub() {
}

void atomicSub() {
}

void atomicSub() {
}

void atomicSub() {
}

void atomicSub() {
}

void workgroupBarrier() {
}

void atomicMax() {
}

void atomicMax() {
}

void atomicMax() {
}

void atomicMax() {
}

void atomicMax() {
}

void atomicMax() {
}

void atomicMax() {
}

void atomicMax() {
}

void workgroupBarrier() {
}

void atomicMin() {
}

void atomicMin() {
}

void atomicMin() {
}

void atomicMin() {
}

void atomicMin() {
}

void atomicMin() {
}

void atomicMin() {
}

void atomicMin() {
}

void workgroupBarrier() {
}

void atomicAnd() {
}

void atomicAnd() {
}

void atomicAnd() {
}

void atomicAnd() {
}

void atomicAnd() {
}

void atomicAnd() {
}

void atomicAnd() {
}

void atomicAnd() {
}

void workgroupBarrier() {
}

void atomicOr() {
}

void atomicOr() {
}

void atomicOr() {
}

void atomicOr() {
}

void atomicOr() {
}

void atomicOr() {
}

void atomicOr() {
}

void atomicOr() {
}

void workgroupBarrier() {
}

void atomicXor() {
}

void atomicXor() {
}

void atomicXor() {
}

void atomicXor() {
}

void atomicXor() {
}

void atomicXor() {
}

void atomicXor() {
}

void atomicXor() {
}

void atomicExchange() {
}

void atomicExchange() {
}

void atomicExchange() {
}

void atomicExchange() {
}

void atomicExchange() {
}

void atomicExchange() {
}

void atomicExchange() {
}

void atomicExchange() {
}

void atomicCompareExchangeWeak() {
}

void atomicCompareExchangeWeak() {
}

void atomicCompareExchangeWeak() {
}

void atomicCompareExchangeWeak() {
}

void atomicCompareExchangeWeak() {
}

void atomicCompareExchangeWeak() {
}

void atomicCompareExchangeWeak() {
}

void atomicCompareExchangeWeak() {
}
