// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


void main() {
}

void pack4xI8() {
}

void pack4xU8() {
}

void unpack4x8snorm() {
}

void unpack4x8unorm() {
}

void unpack2x16snorm() {
}

void unpack2x16unorm() {
}
