// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float2 pos;
    float2 vel;
};
struct Struct_3 {
    float deltaT;
    float rule1Distance;
    float rule2Distance;
    float rule3Distance;
    float rule1Scale;
    float rule2Scale;
    float rule3Scale;
};
struct Struct_5 {
    void particles;
};
uint global_0 = 0u;
Struct_3 global_1 : register(b0);
Struct_5 global_2 : register(u1);
Struct_5 global_3 : register(u2);

[numthreads(1, 1, 1)]
void main() {
}

void distance() {
}

void distance() {
}

void distance() {
}

void normalize() {
}

void clamp() {
}

void length() {
}
