// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_1 {
    uint t;
};
uint global_0 : register(u0);
void global_1 : register(u1);
void global_2 : register(b2);
void global_3 : register(u3);
void global_4 : register(u4);
void global_5 : register(u0);

[numthreads(1, 1, 1)]
void main() {
}
