// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    uint a;
    void b;
    void c;
};
Struct_3 global_0 : register(u0);

uint fetch_add_atomic() {
    return atomicAdd(&global_0.a, 0u);
}

void atomicAdd() {
}

uint fetch_add_atomic_static_sized_array(int i) {
    return atomicAdd(&global_0.b[i], 0u);
}

void atomicAdd() {
}

uint fetch_add_atomic_dynamic_sized_array(int i) {
    return atomicAdd(&global_0.c[i], 0u);
}

void atomicAdd() {
}

uint exchange_atomic() {
    return atomicExchange(&global_0.a, 0u);
}

void atomicExchange() {
}

uint exchange_atomic_static_sized_array(int i) {
    return atomicExchange(&global_0.b[i], 0u);
}

void atomicExchange() {
}

uint exchange_atomic_dynamic_sized_array(int i) {
    return atomicExchange(&global_0.c[i], 0u);
}

void atomicExchange() {
}

uint fetch_add_atomic_dynamic_sized_array_static_index() {
    return atomicAdd(&global_0.c[1000], 0u);
}

void atomicAdd() {
}

uint exchange_atomic_dynamic_sized_array_static_index() {
    return atomicExchange(&global_0.c[1000], 0u);
}

void atomicExchange() {
}

[numthreads(1, 1, 1)]
void main() {
}
