// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

Texture2D<float> global_0 : register(t0);
Texture2D<float> global_1 : register(t1);
Texture2D<float> global_2 : register(t2);

float test_textureLoad_depth_2d(int2 coords, int level) {
    return textureLoad(global_0, coords, level);
}

void textureLoad() {
}

float test_textureLoad_depth_2d_array_u(int2 coords, uint index, int level) {
    return textureLoad(global_1, coords, index, level);
}

void textureLoad() {
}

float test_textureLoad_depth_2d_array_s(int2 coords, int index, int level) {
    return textureLoad(global_1, coords, index, level);
}

void textureLoad() {
}

float test_textureLoad_depth_multisampled_2d(int2 coords, int _sample) {
    return textureLoad(global_2, coords, _sample);
}

void textureLoad() {
}

struct fragment_shader_Output {
    float4 color : SV_Target;
};
fragment_shader_Output fragment_shader() {
    fragment_shader_Output stage_out;
    return stage_out;
}
