// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

Texture1D<float4> global_0 : register(t0);
Texture2D<float4> global_1 : register(t1);
Texture2DArray<float4> global_2 : register(t2);
Texture3D<float4> global_3 : register(t3);
Texture2DMS<float4> global_4 : register(t4);
texture_storage_1d<rgba8unorm, write> global_5 : register(t5);
texture_storage_2d<rgba8unorm, write> global_6 : register(t6);
texture_storage_2d_array<rgba8unorm, write> global_7 : register(t7);
texture_storage_3d<rgba8unorm, write> global_8 : register(t8);

float4 test_textureLoad_1d(int coords, int level) {
    return textureLoad(global_0, coords, level);
}

void textureLoad() {
}

float4 test_textureLoad_2d(int2 coords, int level) {
    return textureLoad(global_1, coords, level);
}

void textureLoad() {
}

float4 test_textureLoad_2d_array_u(int2 coords, uint index, int level) {
    return textureLoad(global_2, coords, index, level);
}

void textureLoad() {
}

float4 test_textureLoad_2d_array_s(int2 coords, int index, int level) {
    return textureLoad(global_2, coords, index, level);
}

void textureLoad() {
}

float4 test_textureLoad_3d(int3 coords, int level) {
    return textureLoad(global_3, coords, level);
}

void textureLoad() {
}

float4 test_textureLoad_multisampled_2d(int2 coords, int _sample) {
    return textureLoad(global_4, coords, _sample);
}

void textureLoad() {
}

void test_textureStore_1d(int coords, float4 value) {
}

void textureStore() {
}

void test_textureStore_2d(int2 coords, float4 value) {
}

void textureStore() {
}

void test_textureStore_2d_array_u(int2 coords, uint array_index, float4 value) {
}

void textureStore() {
}

void test_textureStore_2d_array_s(int2 coords, int array_index, float4 value) {
}

void textureStore() {
}

void test_textureStore_3d(int3 coords, float4 value) {
}

void textureStore() {
}

struct fragment_shader_Output {
    float4 color : SV_Target;
};
fragment_shader_Output fragment_shader() {
    fragment_shader_Output stage_out;
    return stage_out;
}
