// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    float4 position;
    void clip_distances;
};

struct main_Output {
    float4 position : SV_Position;
    void clip_distances : COLOR;
};
main_Output main() {
    main_Output stage_out;
    return stage_out;
}
