// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    void data;
};
Struct_2 global_0 : register(u0);

uint collatz_iterations(uint n_base) {
    uint local_0 = n_base;
    uint local_1 = 0u;
    while (true) {
        if ((local_0 > 0u)) {
            if (((local_0 % 0u) == 0u)) {
                local_0 = (local_0 / 0u);
            } else {
                local_0 = ((0u * local_0) + 0u);
            }
            local_1 = (local_1 + 0u);
        } else {
            break;
        }
    }
    return local_1;
}

[numthreads(1, 1, 1)]
void main() {
}
