// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

float global_0 = -(65504.0f);
float global_1 = 65504.0f;
float global_2 = -(3.4028235E38f);
float global_3 = 3.4028235E38f;
float global_4 = -(Infinity.0f);
float global_5 = Infinity.0f;

int test_f16_to_i32(half f) {
    return int(f);
}

uint test_f16_to_u32(half f) {
    return uint(f);
}

int test_f16_to_i64(half f) {
    return int(f);
}

uint test_f16_to_u64(half f) {
    return uint(f);
}

int test_f32_to_i32(float f) {
    return int(f);
}

uint test_f32_to_u32(float f) {
    return uint(f);
}

int test_f32_to_i64(float f) {
    return int(f);
}

uint test_f32_to_u64(float f) {
    return uint(f);
}

int2 test_f16_to_i32_vec(half2 f) {
    return int2(f);
}

uint2 test_f16_to_u32_vec(half2 f) {
    return uint2(f);
}

int2 test_f16_to_i64_vec(half2 f) {
    return int2(f);
}

uint2 test_f16_to_u64_vec(half2 f) {
    return uint2(f);
}

int2 test_f32_to_i32_vec(float2 f) {
    return int2(f);
}

uint2 test_f32_to_u32_vec(float2 f) {
    return uint2(f);
}

int2 test_f32_to_i64_vec(float2 f) {
    return int2(f);
}

uint2 test_f32_to_u64_vec(float2 f) {
    return uint2(f);
}

void test_const_eval() {
    int local_0 = int(global_0);
    int local_1 = int(global_1);
    uint local_2 = uint(global_0);
    uint local_3 = uint(global_1);
    int local_4 = int(global_0);
    int local_5 = int(global_1);
    uint local_6 = uint(global_0);
    uint local_7 = uint(global_1);
    int local_8 = int(global_2);
    int local_9 = int(global_3);
    uint local_10 = uint(global_2);
    uint local_11 = uint(global_3);
    int local_12 = int(global_2);
    int local_13 = int(global_3);
    uint local_14 = uint(global_2);
    uint local_15 = uint(global_3);
    int local_16 = int(global_4);
    int local_17 = int(global_5);
    uint local_18 = uint(global_4);
    uint local_19 = uint(global_5);
    int local_20 = int(global_4);
    int local_21 = int(global_5);
    uint local_22 = uint(global_4);
    uint local_23 = uint(global_5);
}

[numthreads(1, 1, 1)]
void main() {
    test_const_eval();
    test_f16_to_i32(1.0f);
    test_f16_to_u32(1.0f);
    test_f16_to_i64(1.0f);
    test_f16_to_u64(1.0f);
    test_f32_to_i32(1.0f);
    test_f32_to_u32(1.0f);
    test_f32_to_i64(1.0f);
    test_f32_to_u64(1.0f);
    test_f16_to_i32_vec(float2(1, 2));
    test_f16_to_u32_vec(float2(1, 2));
    test_f16_to_i64_vec(float2(1, 2));
    test_f16_to_u64_vec(float2(1, 2));
    test_f32_to_i32_vec(float2(1, 2));
    test_f32_to_u32_vec(float2(1, 2));
    test_f32_to_i64_vec(float2(1, 2));
    test_f32_to_u64_vec(float2(1, 2));
}
