// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

Texture2D<float> global_0 : register(t4);
sampler_comparison global_1 : register(t5);

struct fragment_Output {
    float4 color : SV_Target;
};
fragment_Output fragment() {
    fragment_Output stage_out;
    return stage_out;
}

void textureSampleCompare() {
}
