// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float3 position;
    float3 color;
};
struct Struct_4 {
    float4 clip_position;
    float3 color;
};

struct vs_main_Output {
    float4 clip_position : SV_Position;
    float3 color : TEXCOORD0;
};
vs_main_Output vs_main() {
    vs_main_Output stage_out;
    return stage_out;
}

struct fs_main_Output {
    float4 color : SV_Target;
};
fs_main_Output fs_main() {
    fs_main_Output stage_out;
    return stage_out;
}
