// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float4 output0;
    float4 output1;
};

struct main_Output {
    float4 output0 : TEXCOORD0;
    float4 output1 : TEXCOORD0;
};
main_Output main() {
    main_Output stage_out;
    return stage_out;
}
