// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    uint index;
    float2 double;
};
struct Struct_5 {
    float4 color;
    uint primitive_index;
};
Struct_3 global_0;

struct main_Output {
    float4 color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    return stage_out;
}
