// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_4 {
    float scalar_f16;
    float scalar_f32;
    float2 vec2_f16;
    float2 vec2_f32;
    float3 vec3_f16;
    float3 vec3_f32;
    float4 vec4_f16;
    float4 vec4_f32;
};

struct test_direct_Input {
    float scalar_f16 : TEXCOORD0;
    float scalar_f32 : TEXCOORD1;
    float2 vec2_f16 : TEXCOORD2;
    float2 vec2_f32 : TEXCOORD3;
    float3 vec3_f16 : TEXCOORD4;
    float3 vec3_f32 : TEXCOORD5;
    float4 vec4_f16 : TEXCOORD6;
    float4 vec4_f32 : TEXCOORD7;
};
struct test_direct_Output {
    float scalar_f16 : TEXCOORD0;
    float scalar_f32 : TEXCOORD1;
    float2 vec2_f16 : TEXCOORD2;
    float2 vec2_f32 : TEXCOORD3;
    float3 vec3_f16 : TEXCOORD4;
    float3 vec3_f32 : TEXCOORD5;
    float4 vec4_f16 : TEXCOORD6;
    float4 vec4_f32 : TEXCOORD7;
};
test_direct_Output test_direct(test_direct_Input stage_in) {
    test_direct_Output stage_out;
    float scalar_f16 = stage_in.scalar_f16;
    float scalar_f32 = stage_in.scalar_f32;
    float2 vec2_f16 = stage_in.vec2_f16;
    float2 vec2_f32 = stage_in.vec2_f32;
    float3 vec3_f16 = stage_in.vec3_f16;
    float3 vec3_f32 = stage_in.vec3_f32;
    float4 vec4_f16 = stage_in.vec4_f16;
    float4 vec4_f32 = stage_in.vec4_f32;
    return stage_out;
}

struct test_struct_Output {
    float scalar_f16 : TEXCOORD0;
    float scalar_f32 : TEXCOORD1;
    float2 vec2_f16 : TEXCOORD2;
    float2 vec2_f32 : TEXCOORD3;
    float3 vec3_f16 : TEXCOORD4;
    float3 vec3_f32 : TEXCOORD5;
    float4 vec4_f16 : TEXCOORD6;
    float4 vec4_f32 : TEXCOORD7;
};
test_struct_Output test_struct() {
    test_struct_Output stage_out;
    return stage_out;
}

struct test_copy_input_Output {
    float scalar_f16 : TEXCOORD0;
    float scalar_f32 : TEXCOORD1;
    float2 vec2_f16 : TEXCOORD2;
    float2 vec2_f32 : TEXCOORD3;
    float3 vec3_f16 : TEXCOORD4;
    float3 vec3_f32 : TEXCOORD5;
    float4 vec4_f16 : TEXCOORD6;
    float4 vec4_f32 : TEXCOORD7;
};
test_copy_input_Output test_copy_input() {
    test_copy_input_Output stage_out;
    return stage_out;
}

struct test_return_partial_Output {
    float color : SV_Target;
};
test_return_partial_Output test_return_partial() {
    test_return_partial_Output stage_out;
    return stage_out;
}

struct test_component_access_Output {
    float scalar_f16 : TEXCOORD0;
    float scalar_f32 : TEXCOORD1;
    float2 vec2_f16 : TEXCOORD2;
    float2 vec2_f32 : TEXCOORD3;
    float3 vec3_f16 : TEXCOORD4;
    float3 vec3_f32 : TEXCOORD5;
    float4 vec4_f16 : TEXCOORD6;
    float4 vec4_f32 : TEXCOORD7;
};
test_component_access_Output test_component_access() {
    test_component_access_Output stage_out;
    return stage_out;
}
