// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

float global_0 = 1;
float global_1 = 0.0f;

float f(float x) {
    float local_0 = (0.0f + 0.0f);
    float local_1 = (local_0 + float(5));
    float local_2 = -(0.0f);
    return (((x + local_0) + global_1) + 0.0f);
}

[numthreads(1, 1, 1)]
void main() {
}
