// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


int index_arg_array(void a, int i) {
    return a[i];
}

int index_let_array(int i, int j) {
    void local_0 = void(float(1, 2), float(3, 4));
    return local_0[i][j];
}

float index_let_matrix(int i, int j) {
    float2x2 local_0 = float2x2(1, 2, 3, 4);
    return local_0[i][j];
}

float4 index_let_array_1d(uint vi) {
    void local_0 = void(1, 2, 3, 4, 5);
    int local_1 = local_0[vi];
    return float4(int4(local_1));
}

struct main_Output {
    float4 position : SV_Position;
};
main_Output main() {
    main_Output stage_out;
    return stage_out;
}
