// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float4 position;
    float _varying;
};
struct Struct_4 {
    float depth;
    uint sample_mask;
    float color;
};
struct Struct_5 {
    uint index;
};
void global_0;

struct vertex_two_structs_Output {
    float4 position : SV_Position;
};
vertex_two_structs_Output vertex_two_structs() {
    vertex_two_structs_Output stage_out;
    return stage_out;
}
