// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    void values;
};
Struct_2 global_0;
Struct_2 global_1;
Struct_2 global_2;
Struct_2 global_3;

[numthreads(1, 1, 1)]
void main() {
}
