// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_1 {
    int x;
};
int global_0 = 1;
Texture2D<float4> global_1 : register(t0);
SamplerState global_2 : register(t1);

void statement() {
}

Struct_1 returns() {
    return Struct_1(global_0);
}

void call() {
    Struct_1 local_0 = returns();
    float local_1 = float(global_0);
    Texture2D<float4> local_2 = textureSample(global_1, global_2, float2(local_1));
}

void textureSample() {
}

void main() {
}
