// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

int global_0;
uint global_1;

[numthreads(1, 1, 1)]
void f() {
}

void atomicCompareExchangeWeak(void arg_0, uint arg_1, uint arg_2) {
}
