// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    int3 chunk;
    uint texture_index;
};
struct Struct_6 {
    float4 clip_position;
};

struct vs_main_Output {
    float4 clip_position : SV_Position;
};
vs_main_Output vs_main() {
    vs_main_Output stage_out;
    return stage_out;
}
