// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float3 a;
};
struct Struct_4 {
    void a;
    float b;
};
struct Struct_6 {
    float4x3 a;
    float b;
};
struct Struct_7 {
    Struct_2 a;
    float b;
};
Struct_4 global_0 : register(b1);
Struct_6 global_1 : register(b2);
Struct_7 global_2 : register(b0);
