// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


struct fs_main_Input {
    void v : TEXCOORD0;
};
struct fs_main_Output {
    float4 color : SV_Target;
};
fs_main_Output fs_main(fs_main_Input stage_in) {
    fs_main_Output stage_out;
    void v = stage_in.v;
    return stage_out;
}
