// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


void takes_ptr(int* p) {
}

void takes_array_ptr(void* p) {
}

void takes_vec_ptr(int2* p) {
}

void takes_mat_ptr(float2x2* p) {
}

void argument(void* v, uint i) {
}

void argument_nested_x3(void* v, uint i, uint j) {
}

void index_from_self(void* v, uint i) {
}

void local_var_from_arg(void a, uint i) {
    void local_0 = a;
}

void let_binding(void* a, uint i) {
    void local_0 = &a[i];
    void local_1 = &a[0];
}

void local_var(uint i) {
    void local_0 = void(1, 2, 3, 4);
}

void argument_nested_x2(void* v, uint i, uint j) {
}

void mat_vec_ptrs(void* pv, void* pm, uint i) {
}

[numthreads(1, 1, 1)]
void main() {
}
