// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    void arr;
};
Struct_2 global_0 : register(u0);

void f() {
    float2x2 local_0;
    void local_1 = /* unsupported expression: ValuePointer */;
    local_1 = float2(10.0f);
}

void index_unsized(int i, uint v) {
    Struct_2* local_0 = /* unsupported expression: ValuePointer */;
    uint local_1 = local_0.arr[i];
    local_0.arr[i] = (local_1 + v);
}

void index_dynamic_array(int i, uint v) {
    void* local_0 = /* unsupported expression: ValuePointer */;
    uint local_1 = local_0[i];
    local_0[i] = (local_1 + v);
}

[numthreads(1, 1, 1)]
void main() {
}
