// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


struct func_Output {
    float4 color : SV_Target;
};
func_Output func() {
    func_Output stage_out;
    return float4(float(index), 1.0f, 1.0f, 1.0f);
    return stage_out;
}
