// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_1 {
    float multiplier;
};
struct Struct_3 {
    float4 color;
};
Struct_1 global_0;

struct vert_main_Input {
    float2 pos : TEXCOORD0;
};
struct vert_main_Output {
    float4 position : SV_Position;
};
vert_main_Output vert_main(vert_main_Input stage_in) {
    vert_main_Output stage_out;
    float2 pos = stage_in.pos;
    return stage_out;
}

struct main_Output {
    float4 color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    return stage_out;
}
