// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

float global_0 : register(t0);
float global_1 : register(t1);
float global_2 : register(t2);
float global_3 : register(t3);
float2 global_4 : register(b4);
float2 global_5 : register(b0);

struct entry_point_one_Input {
    float4 pos : SV_Position;
};
struct entry_point_one_Output {
    float4 color : SV_Target;
};
entry_point_one_Output entry_point_one(entry_point_one_Input stage_in) {
    entry_point_one_Output stage_out;
    float4 pos = stage_in.pos;
    return stage_out;
}

void textureSample() {
}

struct entry_point_two_Output {
    float4 color : SV_Target;
};
entry_point_two_Output entry_point_two() {
    entry_point_two_Output stage_out;
    return stage_out;
}

void textureSample() {
}

struct entry_point_three_Output {
    float4 color : SV_Target;
};
entry_point_three_Output entry_point_three() {
    entry_point_three_Output stage_out;
    return stage_out;
}

void textureSample() {
}

void textureSample() {
}
