// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

Texture2D<float> global_0 : register(t0);
sampler_comparison global_1 : register(t1);

struct main_Output {
    float color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    return stage_out;
}

void textureSampleCompareLevel() {
}
