// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


void derivatives() {
    float local_0 = dpdx(0.0f);
    float local_1 = dpdy(0.0f);
    float local_2 = fwidth(0.0f);
}

void dpdx() {
}

void dpdy() {
}

void fwidth() {
}

void barriers() {
}

void storageBarrier() {
}

void workgroupBarrier() {
}

void textureBarrier() {
}

struct fragment_Output {
    float4 color : SV_Target;
};
fragment_Output fragment() {
    fragment_Output stage_out;
    return stage_out;
}

[numthreads(1, 1, 1)]
void compute() {
}
