// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_4 {
    float4x4 view_proj;
    uint4 num_lights;
};
struct Struct_6 {
    float4x4 world;
    float4 color;
};
struct Struct_8 {
    float4 proj_position;
    float3 world_normal;
    float4 world_position;
};
struct Struct_9 {
    float4x4 proj;
    float4 pos;
    float4 color;
};
Texture2D<float> global_0 : register(t2);
sampler_comparison global_1 : register(t3);
float3 global_2 = float3(0.05f, 0.05f, 0.05f);
uint global_3 = 0u;
Struct_4 global_4 : register(b0);
Struct_6 global_5 : register(b0);
void global_6 : register(u1);
void global_7 : register(b1);

float fetch_shadow(uint light_id, float4 homogeneous_coords) {
    if ((homogeneous_coords[3] <= 0.0f)) {
        return 1.0f;
    }
    float2 local_0 = float2(0.5f, -(0.5f));
    float local_1 = (1.0f / homogeneous_coords[3]);
    float2 local_2 = (((homogeneous_coords.xy * local_0) * local_1) + float2(0.5f, 0.5f));
    return textureSampleCompareLevel(global_0, global_1, local_2, int(light_id), (homogeneous_coords[2] * local_1));
}

void textureSampleCompareLevel() {
}

struct vs_main_Input {
    int4 position : TEXCOORD0;
    int4 normal : TEXCOORD1;
};
struct vs_main_Output {
    float4 proj_position : SV_Position;
    float3 world_normal : TEXCOORD0;
    float4 world_position : TEXCOORD1;
};
vs_main_Output vs_main(vs_main_Input stage_in) {
    vs_main_Output stage_out;
    int4 position = stage_in.position;
    int4 normal = stage_in.normal;
    return stage_out;
}

struct fs_main_Output {
    float4 color : SV_Target;
};
fs_main_Output fs_main() {
    fs_main_Output stage_out;
    return stage_out;
}

void normalize() {
}

void normalize() {
}

void max() {
}

void dot() {
}

void min() {
}

struct fs_main_without_storage_Output {
    float4 color : SV_Target;
};
fs_main_without_storage_Output fs_main_without_storage() {
    fs_main_without_storage_Output stage_out;
    return stage_out;
}

void normalize() {
}

void normalize() {
}

void max() {
}

void dot() {
}

void min() {
}
