// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    float4 position;
    float3 uv;
};
struct Struct_5 {
    float4x4 proj_inv;
    float4x4 view;
};
TextureCube<float4> global_0 : register(t1);
SamplerState global_1 : register(t2);
Struct_5 global_2 : register(b0);

struct fs_main_Output {
    float4 color : SV_Target;
};
fs_main_Output fs_main() {
    fs_main_Output stage_out;
    return stage_out;
}

void textureSample() {
}

struct vs_main_Output {
    float4 position : SV_Position;
    float3 uv : TEXCOORD0;
};
vs_main_Output vs_main() {
    vs_main_Output stage_out;
    return stage_out;
}

void transpose() {
}
