// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


bool test_any_and_all_for_bool() {
    bool local_0 = any(true);
    return all(local_0);
}

void any() {
}

void all() {
}

struct derivatives_Input {
    float4 foo : SV_Position;
};
struct derivatives_Output {
    float4 color : SV_Target;
};
derivatives_Output derivatives(derivatives_Input stage_in) {
    derivatives_Output stage_out;
    float4 foo = stage_in.foo;
    return stage_out;
}

void dpdxCoarse() {
}

void dpdyCoarse() {
}

void fwidthCoarse() {
}

void dpdxFine() {
}

void dpdyFine() {
}

void fwidthFine() {
}

void dpdx() {
}

void dpdy() {
}

void fwidth() {
}
