// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

texture_storage_2d<r32float, read> global_0 : register(t0);
texture_storage_2d<rg32float, read> global_1 : register(t1);
texture_storage_2d<rgba32float, read> global_2 : register(t2);
texture_storage_2d<r32float, write> global_3 : register(t0);
texture_storage_2d<rg32float, write> global_4 : register(t1);
texture_storage_2d<rgba32float, write> global_5 : register(t2);

[numthreads(1, 1, 1)]
void csLoad() {
}

void textureLoad() {
}

void textureLoad() {
}

void textureLoad() {
}

[numthreads(1, 1, 1)]
void csStore() {
}

void textureStore() {
}

void textureStore() {
}

void textureStore() {
}
