// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_1 {
    uint num_subgroups;
    uint subgroup_size;
};

[numthreads(1, 1, 1)]
void main() {
}

void subgroupBallot() {
}

void subgroupBallot() {
}

void subgroupAll() {
}

void subgroupAny() {
}

void subgroupAdd() {
}

void subgroupMul() {
}

void subgroupMin() {
}

void subgroupMax() {
}

void subgroupAnd() {
}

void subgroupOr() {
}

void subgroupXor() {
}

void subgroupExclusiveAdd() {
}

void subgroupExclusiveMul() {
}

void subgroupInclusiveAdd() {
}

void subgroupInclusiveMul() {
}

void subgroupBroadcastFirst() {
}

void subgroupBroadcast() {
}

void subgroupShuffle() {
}

void subgroupShuffleDown() {
}

void subgroupShuffleUp() {
}

void subgroupShuffleXor() {
}

void quadBroadcast() {
}

void quadSwapX() {
}

void quadSwapY() {
}

void quadSwapDiagonal() {
}
