// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

void global_0;
void global_1;
void global_2 : register(u0);
void global_3 : register(u1);

[numthreads(1, 1, 1)]
void main() {
}
