// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

float global_0 : register(t0);
float global_1 : register(t1);

float4 test(float t) {
    float local_0 = textureSampleBaseClampToEdge(t, global_1, float2(0.0f));
    float local_1 = textureLoad(t, float2(0));
    float local_2 = textureLoad(t, float2(0u));
    float local_3 = textureDimensions(t);
    return (((local_0 + local_1) + local_2) + float2(local_3).xyxy);
}

void textureSampleBaseClampToEdge() {
}

void textureLoad() {
}

void textureLoad() {
}

void textureDimensions() {
}

struct fragment_main_Output {
    float4 color : SV_Target;
};
fragment_main_Output fragment_main() {
    fragment_main_Output stage_out;
    return stage_out;
}

struct vertex_main_Output {
    float4 position : SV_Position;
};
vertex_main_Output vertex_main() {
    vertex_main_Output stage_out;
    return stage_out;
}

[numthreads(1, 1, 1)]
void compute_main() {
}
