// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

float global_0 : register(t0);
float global_1 : register(t1);

float4 test(float Passed_Texture, float Passed_Sampler) {
    return textureSample(Passed_Texture, Passed_Sampler, float2(0.0f, 0.0f));
}

void textureSample() {
}

struct main_Output {
    float4 color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    return stage_out;
}
