// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

uint global_0 = 0u;
void global_1;

[numthreads(1, 1, 1)]
void test_workgroupUniformLoad() {
}

void workgroupUniformLoad() {
}

void workgroupBarrier() {
}
