// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_5 {
    void arr;
    float atom;
    void atom_arr;
};
void global_0;
Struct_5 global_1;

[numthreads(1, 1, 1)]
void main() {
}
